### ISSUE TITLE
Remove option to quit out from report

### ISSUE THREAD

**Issue by Sjokomelk** [Tommy228/TTTDamagelogs#100]
Right now you can click out of the report. http://puu.sh/e6Gjb/d0ed2d4990.png
Only keep forgive and keep.

**Comment by CSchulz** [comment]
I think close would be also an option but it should be shown next round or something like that.

Sometimes the response pops up 1 second before round start and in such cases you close it to be able to play instead of reading the answer.

**Comment by Tommy228** [comment]
I still removed it, maybe @CSchulz's idea will be done later.
