### ISSUE TITLE
Pling sound outside of the game?

### ISSUE THREAD

**Issue by Sjokomelk** [Tommy228/TTTDamagelogs#101]
Sometimes I'm just sitting AFK on the server, watching out for RDM. It would be great if a pling sound could be played if the game was minimized and a report was either submitted/updated.

**Comment by CSchulz** [comment]
:+1:

**Comment by BuilderGaming** [comment]
I like this, Agreed

**Comment by HDG-MrDeeJay** [comment]
you can do this is your settings for gmod, play sound while window isn't in focus.

**Comment by CSchulz** [comment]
But you will still here the shooting sounds and so on. It was more like that you will be notified if there is a report.

One possibility to achieve it would be the HTML engine and play there some sounds.

**Comment by HDG-MrDeeJay** [comment]
hmm.. the awesomium process DOES operate separately to the source engine 
entirely. I know for a fact that is what powers loading screens. 
Provided you dont mute that process in Windows (like I have), you could 
use html to play it...........

....... or you could do what I suggested.

**Comment by CSchulz** [comment]
I have muted it too. :laughing: 

Perhaps there is way to mute all sounds ingame (programmatically). If I have some time I will dig into it and post my research results here.

**Comment by Joschasa** [comment]
Maybe a mode, where damagelogs just sets your  volume to 0. In case of a notification, the volume is raised for a second, then muted again.

**Comment by CSchulz** [comment]
I think there are two ways to implement it using lua:

- Muting all sounds see http://wiki.garrysmod.com/page/Enums/CHAN and activate play sound while window isn't in focus.
- Set volume to 0 and increase it for a report
