### ISSUE TITLE
Experimental: aslay not showing after typing only when player is slayed.

### ISSUE THREAD

**Issue by ZachPL** [Tommy228/TTTDamagelogs#106]
When typing aslay there is no confirmation like there was that the command went through only once the round starts and the player is slain that it shows. 

Currently is very confusing to my admins

**Comment by Tommy228** [comment]
Ok I can see why it happens I'll fix it in a few hours, does everything else work fine?

**Comment by ZachPL** [comment]
Seems to, there might be an issue where if you don't finish a report and try to put a conclusion nothing happens, but I need to test it again

**Comment by Tommy228** [comment]
> Seems to, there might be an issue where if you don't finish a report and try to put a conclusion nothing happens, but I need to test it again
Intentional. I don't see why you would want to put a conclusion before finishing the report.

**Comment by ZachPL** [comment]
Yeah it was an accident, but maybe it should notify you to finish the report first.

**Comment by Tommy228** [comment]
Yup, I'll add a notification.
