### ISSUE TITLE
Finish report/canceled by victim weird behaviour/bug?

### ISSUE THREAD

**Issue by copyyy** [Tommy228/TTTDamagelogs#110]
I reported someone.
He respond.
I set report to canceled.
Then I was not able to finish the report because it was canceled by the victim, so wasn't able to set a conclusion BUT another admin was able to finish it (didn't show up for me, still said "Canceled by victim") and set a conclusion which was shown up for me.

**Comment by Tommy228** [comment]
Does it happen really often?

**Comment by copyyy** [comment]
Sorry, haven't seen your respond. Saw it once, but not playing so often anymore, so I'll just try it next time!
