### ISSUE TITLE
Unfinished reports indicator

### ISSUE THREAD

**Issue by CyberAP** [Tommy228/TTTDamagelogs#118]
Quite often there are some reports that don't get any attention because admins forget about them. Maybe we should have a tiny indicator that shows how many reports have a «waiting» state? In that case we won't need to open RDM manager every single round to double-check that there are no unfinished reports.

**Comment by Tommy228** [comment]
You mean on the HUD ? Where can I display it, for example?

**Comment by CyberAP** [comment]
I mean the whole screen space. It can be just a red circle with a number on the right or left top corner on the screen.
But one important thing is that it must be shown only to dead admins, so it won't disturb during the game.

**Comment by Linkfan123** [comment]
+1
