### ISSUE TITLE
Death Scene Bug

### ISSUE THREAD

**Issue by ZachPL** [Tommy228/TTTDamagelogs#121]
[ERROR] lua/damagelogs/cl_recording.lua:360: bad argument #1 to 'ClientsideModel' (string expected, got nil)
  1. ClientsideModel - [C]:-1
   2. fn - lua/damagelogs/cl_recording.lua:360
    3. unknown - addons/ulib/lua/ulib/shared/hook.lua:183

started to spam console

**Comment by BytewaveMLP** [comment]
Seems like this is caused when an entity with no model exists in the map.
I'm not sure how ClientsideModel() works, but you could probably do something like
```lua
ClientSideModel(v.model or "", ...)
```

**Comment by Tommy228** [comment]
Done in exp
