### ISSUE TITLE
Ability to change the default aslay reason?

### ISSUE THREAD

**Issue by Jerpy** [Tommy228/TTTDamagelogs#122]
I tried doing this in the script, but even changing it from "No reason specified" to "RDM", it still comes up as no reason specified. Where would I go about doing this, and if possible, could it be added to the config in a later version? Thanks.

**Comment by Tommy228** [comment]
It can be changed on *ulx/sv_autoslay.lua*. I'll add an option for that later

**Comment by Jerpy** [comment]
I tried that, and I did this

	autoslay:addParam({ 
		type=ULib.cmds.StringArg, 
		hint="slay reason", 
		default = "RDM",
		ULib.cmds.optional,
		ULib.cmds.takeRestOfLine
	})

That's for regular aslay, and I did the same thing for aslayid removing the default and putting in "RDM" as an example. For some reason "No reason specified" is still coming up

**Comment by copyyy** [comment]
Can't look at the whole code atm (ULX/ULib) but try to remove the ULib,cmds.optional, maybe it ignores the default when it's set to optional.

**Comment by Jerpy** [comment]
Just tried that, sadly did not work. All it did was require a reason no matter the situation, so even when removing an aslay you need to give a reason. Removes default from being a thing, basically.

**Comment by copyyy** [comment]
OK, just looked at the code. by default it is already optional and has a default so it should be working when changing.. Can't try it atm, maybe someone else can?
And, just need to ask that, you really edited the right file (lua/damagelogs/ulx/sh_autoslay.lua), saved it and made a mapchange?

**Comment by Jerpy** [comment]
Yeah, thats what I edited and I've even done server restarts since that reason has been in there. Hasn't changed it at all.

**Comment by Tommy228** [comment]
[Line 96 of *ulx/sv_autoslay.lua*](https://github.com/Tommy228/TTTDamagelogs/blob/master/lua/damagelogs/ulx/sv_autoslay.lua#L96). It looks like the "default" parameter of ULX commands doesn't work, so the default reason is there.

**Comment by Tommy228** [comment]
Done
