### ISSUE TITLE
Victim Slay shows wrong title in reason text field

### ISSUE THREAD

**Issue by doctorluk** [Tommy228/TTTDamagelogs#124]
Right click an RDM report and slay the Victim using a custom reason.
The following window will say
> Please write the reason why you want to slay REPORTED PLAYER

instead of using the Victim's name.

**Comment by BuilderGaming** [comment]
That is possibly the easiest thing to fix. Let me post a photo on how to do it then

**Comment by BuilderGaming** [comment]
nvm its been fixed please close
