### ISSUE TITLE
Damagelogs causing server crash

### ISSUE THREAD

**Issue by soja92** [Tommy228/TTTDamagelogs#130]
I have been trying to diagnose crashing issues on my TTT server for the past week or so, and after stripping most addons I have narrowed down what I think is the cause, damagelogs.

Here are the images of the crash I get on my test server. This happens usually when a player joins after the server being idle for a while.
http://i.gflclan.com/Screenshot_02-04-15-18-37-33.png
http://i.gflclan.com/Screenshot_02-02-15-22-27-47.png

If the mdmp files from these crashes would be helpful, please contact me on steam http://steamcommunity.com/id/soja992

Here are the addons installed on the server:
chattags(private chat tags plugin)
Jigsaw Player Model
lara(player model)
MySqlOO
Tda Megurine Luka Append (v2) (another player model)
TTT ULX Commands
ulib
ulx

**Comment by Tommy228** [comment]
Do you use SQLite or MySQL ? It might be caused by SQLite.

**Comment by soja92** [comment]
sqlite

**Comment by Tommy228** [comment]
Try with MySQL then. I think it will fix the crash issue
