### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by MrUnknownGamer** [Tommy228/TTTDamagelogs#131]
Help wanted tag.

As ive mentioned the body ID does not work. Would love it if someone could help me :)

**Comment by Tommy228** [comment]
I as said on the other topic, show me the result of `lua_run PrintTable(Damagelog.DamageTable)` after identifying a body.

**Comment by BuilderGaming** [comment]
Im not the BEST coder. What is lua_run PrintTable(Damagelog.DamageTable)

**Comment by BuilderGaming** [comment]
> PrintTable(Damagelog.DamageTable)...
{
1:
{
round = 1
infos:
{
2 = 1
5 = weapon_ttt_harpoon
3 = STEAM_0:0:84796290
1 = Unrecognized Gamer
}
id = 10
type = WEP
time = 13
}
2:
{
round = 1
infos:
{
2 = 1
5 = Bot03
3 = STEAM_0:0:84796290
7 = BOT
1 = Unrecognized Gamer
4 = quick_traitor
6 = 1
}
id = 9
type = RADIO
time = 21
}
3:
{
round = 1
infos:
{
2 = 1
5 = Bot03
3 = STEAM_0:0:84796290
7 = BOT
1 = Unrecognized Gamer
4 = quick_traitor
6 = 1
}
id = 9
type = RADIO
time = 34
}
4:
{
round = 1
infos:
{
1 = Bot03
2 = 1
3 = Unrecognized Gamer
4 = 1
5 = 448
6 = ttt_harpoon
7 = BOT
8 = STEAM_0:0:84796290
icon:
{
1 = icon16/exclamation.png
}
}
id = 2
type = DMG
time = 35
}
5:
{
round = 1
infos:
{
8 = 1
2 = 1
5 = ttt_harpoon
3 = Bot03
7 = STEAM_0:0:84796290
1 = Unrecognized Gamer
4 = 1
6 = BOT
}
id = 5
type = KILL
time = 35
}
6:
{
round = 1
infos:
{
2 = 1
5 = quick_nobody
3 = STEAM_0:0:84796290
7 = false
1 = Unrecognized Gamer
4 = quick_traitor
6 = false
}
id = 9
type = RADIO
time = 48
}
7:
{
round = 1
infos:
{
4 = 2
1 = Bot06
2 = 0
3 = BOT
}
id = 8
type = KILL
time = 55
}
8:
{
round = 1
infos:
{
8 = STEAM_0:0:84796290
2 = 0
5 = 146
3 = Unrecognized Gamer
7 = BOT
1 = Bot04
4 = 1
6 = weapon_zm_shotgun
}
id = 2
type = DMG
time = 121
}
9:
{
round = 1
infos:
{
8 = 3
2 = 1
5 = weapon_zm_shotgun
3 = Bot04
7 = STEAM_0:0:84796290
1 = Unrecognized Gamer
4 = 0
6 = BOT
}
id = 5
type = KILL
time = 121
}

**Comment by Tommy228** [comment]
Looks like the hook isn't even called.. what's your TTT version? You can see it on init.lua

**Comment by BuilderGaming** [comment]
Trouble in Terrorist Town, version 2014-06-22.

**Comment by BuilderGaming** [comment]
Why isn't Damagelog:EventHook("TTTBodyFound") being called?

**Comment by BuilderGaming** [comment]
Sorry I closed by accident. Reopened

**Comment by Tommy228** [comment]
Well I think that's because your TTT version is outdated.. try using this version : https://github.com/garrynewman/garrysmod/

If it still won't work debugging messages will help.

**Comment by BuilderGaming** [comment]
> PrintTable(Damagelog.DamageTable)...
{
1:
{
round = 1
infos:
{
1 = Bot02
2 = 2
3 = 11
4 = BOT
5 = false
6 = 0
7 = 1
}
id = 4
type = FD
time = 0
}
2:
{
round = 1
infos:
{
1 = Bot05
2 = 0
3 = 4
4 = BOT
5 = false
6 = 3
7 = 2
}
id = 4
type = FD
time = 3
}
3:
{
round = 1
infos:
{
2 = 1
5 = Bot03
3 = STEAM_0:0:84796290
7 = BOT
1 = Unrecognized Gamer
4 = quick_traitor
6 = 0
}
id = 9
type = RADIO
time = 4
}
4:
{
round = 1
infos:
{
8 = STEAM_0:0:84796290
2 = 0
5 = 10
3 = Unrecognized Gamer
7 = BOT
1 = Bot03
4 = 1
6 = swb_acr
}
id = 2
type = DMG
time = 5
}
5:
{
round = 1
infos:
{
8 = STEAM_0:0:84796290
2 = 0
5 = 10
3 = Unrecognized Gamer
7 = BOT
1 = Bot03
4 = 1
6 = swb_acr
}
id = 2
type = DMG
time = 6
}
6:
{
round = 1
infos:
{
2 = 1
5 = Bot03
3 = STEAM_0:0:84796290
7 = BOT
1 = Unrecognized Gamer
4 = quick_traitor
6 = 0
}
id = 9
type = RADIO
time = 6
}
7:
{
round = 1
infos:
{
8 = STEAM_0:0:84796290
2 = 0
5 = 19
3 = Unrecognized Gamer
7 = BOT
1 = Bot03
4 = 1
6 = swb_acr
}
id = 2
type = DMG
time = 8
}
8:
{
round = 1
infos:
{
8 = STEAM_0:0:84796290
2 = 0
5 = 19
3 = Unrecognized Gamer
7 = BOT
1 = Bot03
4 = 1
6 = swb_acr
}
id = 2
type = DMG
time = 8
}
9:
{
round = 1
infos:
{
8 = STEAM_0:0:84796290
2 = 0
5 = 19
3 = Unrecognized Gamer
7 = BOT
1 = Bot03
4 = 1
6 = swb_acr
}
id = 2
type = DMG
time = 8
}
10:
{
round = 1
infos:
{
8 = STEAM_0:0:84796290
2 = 0
5 = 19
3 = Unrecognized Gamer
7 = BOT
1 = Bot03
4 = 1
6 = swb_acr
}
id = 2
type = DMG
time = 8
}
11:
{
round = 1
infos:
{
8 = STEAM_0:0:84796290
2 = 0
5 = 19
3 = Unrecognized Gamer
7 = BOT
1 = Bot03
4 = 1
6 = swb_acr
}
id = 2
type = DMG
time = 9
}
12:
{
round = 1
infos:
{
8 = 1
2 = 1
5 = swb_acr
3 = Bot03
7 = STEAM_0:0:84796290
1 = Unrecognized Gamer
4 = 0
6 = BOT
}
id = 5
type = KILL
time = 9
}
13:
{
round = 1
infos:
{
8 = STEAM_0:0:84796290
2 = 0
5 = 19
3 = Unrecognized Gamer
7 = BOT
1 = Bot04
4 = 1
6 = swb_acr
}
id = 2
type = DMG
time = 58
}
14:
{
round = 1
infos:
{
8 = STEAM_0:0:84796290
2 = 0
5 = 19
3 = Unrecognized Gamer
7 = BOT
1 = Bot04
4 = 1
6 = swb_acr
}
id = 2
type = DMG
time = 59
}
15:
{
round = 1
infos:
{
8 = 2
2 = 1
5 = swb_acr
3 = Bot04
7 = STEAM_0:0:84796290
1 = Unrecognized Gamer
4 = 0
6 = BOT
}
id = 5
type = KILL
time = 59
}
16:
{
round = 1
infos:
{
8 = STEAM_0:0:84796290
2 = 0
5 = 19
3 = Unrecognized Gamer
7 = BOT
1 = Bot01
4 = 1
6 = swb_acr
}
id = 2
type = DMG
time = 101
}
17:
{
round = 1
infos:
{
8 = STEAM_0:0:84796290
2 = 0
5 = 51
3 = Unrecognized Gamer
7 = BOT
1 = Bot01
4 = 1
6 = swb_acr
}
id = 2
type = DMG
time = 101
}
18:
{
round = 1
infos:
{
8 = STEAM_0:0:84796290
2 = 0
5 = 51
3 = Unrecognized Gamer
7 = BOT
1 = Bot01
4 = 1
6 = swb_acr
}
id = 2
type = DMG
time = 101
}
19:
{
round = 1
infos:
{
8 = 3
2 = 1
5 = swb_acr
3 = Bot01
7 = STEAM_0:0:84796290
1 = Unrecognized Gamer
4 = 0
6 = BOT
}
id = 5
type = KILL
time = 101
}
}
