### ISSUE TITLE
Bug aslay from menu

### ISSUE THREAD

**Issue by ZachPL** [Tommy228/TTTDamagelogs#136]
I'm pretty sure this is a bug if someone else can confirm.

Someone reported a player and then that player left, without noticing that they player left I attempted to slay the reported player next round.

Instead of saying it couldn't find the player or adding the slay for next time they joined it  instead added an autoslay to victim reporting the RDM.

Hopefully that explains it well enough.

**Comment by ZachPL** [comment]
This is a pretty serious bug, I'm going to look into it more myself as its becoming a big issue with admins thinking they slayed the reported played but instead slay the victim leading to a lot of mad.

**Comment by comedinha** [comment]
https://github.com/Tommy228/TTTDamagelogs/issues/117

**Comment by Tommy228** [comment]
Fixed.
