### ISSUE TITLE
RDM Manager Error, Round Stuck

### ISSUE THREAD

**Issue by Violat0r** [Tommy228/TTTDamagelogs#137]
Just as soon as a new round was suppose to begin this popped into console:

[ERROR] addons/tttdamagelogs-master/lua/damagelogs/cl_tabs/rdm_manager.lua:303: attempt to index local 'selected' (a nil value)
  1. UpdateReport - addons/tttdamagelogs-master/lua/damagelogs/cl_tabs/rdm_manager.lua:303
   2. func - addons/tttdamagelogs-master/lua/damagelogs/cl_tabs/rdm_manager.lua:395
    3. unknown - lua/includes/modules/net.lua:32

It caused the server to break and didn't allow the next round to begin. I had to reload the map in order to get everything working again.

The server is running version 2.2.1

**Comment by Joschasa** [comment]
That lua error is already fixed in https://github.com/Tommy228/TTTDamagelogs/commit/679bb2a6d24c4e3ddd889d4f3eb966d537cf56a3
I don't think this error had the potential to get the round stuck :/

**Comment by Violat0r** [comment]
Thank you for the quick reply! I am not sure if it was the cause of the round being stuck but it did happen at the same time. It might have just been a coincidence.

**Comment by Tommy228** [comment]
Yeah it's a clientside issue, no way it can get the round stuck. You should check your server logs and find a serverside error.
