### ISSUE TITLE
RDM manager colors messed up after latest gmod update

### ISSUE THREAD

**Issue by ZachPL** [Tommy228/TTTDamagelogs#140]
http://cloud-4.steamusercontent.com/ugc/714157323041619454/5B31E51C4CC4CE6EDB3F74641215A22A65130AA6/

they seem to be breaking half way

http://cloud-4.steamusercontent.com/ugc/714157323041623711/26F17C1A0726CD571F4AD89A2139CFF34191A6BE/

**Comment by Tommy228** [comment]
Well you fixed it
