### ISSUE TITLE
Suggestion: Status update

### ISSUE THREAD

**Issue by MrUnknownGamer** [Tommy228/TTTDamagelogs#141]
So I've been trying to do this and for some reason I can't get it to work. Anyway, so when a staff member puts it "In Progress" it will message the victim saying who is handling their report to know someone is handling their report.

Optional: If the reported player is autoslayin, the player will get a message saying their report was valid! (Must autoslayin by right clicking on report becasue the person may have multiple reports on them)

Optional: If the reported player is slayin: The reported player will get a message saying "{Playername} has reported and their report is valid. You will be slayin!"

Thanks Tommy :D

**Comment by Tommy228** [comment]
Yeah, good ideas and easy. I'll do this

**Comment by MrUnknownGamer** [comment]
Also add a message that would be useful saying "{Name} {SteamID} has left while slayin. They had {number of slays} left.

**Comment by Tommy228** [comment]
Done.
