### ISSUE TITLE
Autoslay steals role

### ISSUE THREAD

**Issue by CyberAP** [Tommy228/TTTDamagelogs#143]
Running latest TTTdamagelogs 2.2.1. If you put autoslay on a player it doesn't prevent him from being detective or a traitor. Although, ulx 'slay next round' works better and makes it that the slay target is always innocent, that way no T or D roles are stolen. I think autoslay should do the same thing.

**Comment by CSchulz** [comment]
The player who gets slayed shall be get punished for his actions. So I would prefer to keep it.

**Comment by CyberAP** [comment]
@CSchulz well you punish other players too, they lose T or D role too. Traitors team may not even spawn because of this bug.

**Comment by Joschasa** [comment]
On our server i modified aslay to skip, if the player is detective.
In my opinion, a dead detective is a punishment for all innocents. Slaying a traitor is harming the other traitors aswell, but i think this has less impact than a dead detective. Moreover I think, that there are enough players, which would consider a slay that spares detectives and traitors to be a rather weak punishment.

**Comment by CSchulz** [comment]
The statement of @Joschasa makes sense. Perhaps make it configurable or just skip detectives.

**Comment by CyberAP** [comment]
@Joschasa this makes game even more disbalanced. Instead of losing Ts and Ds we only lose Ts and they have to fight even more innocent players. Every server has it's own team balance and by slaying non-innocent players we ruin that balance and the game becomes much easier for one of the teams.

**Comment by CSchulz** [comment]
@CyberAP How is your team balance? How many traitors and detectives? I am just curious.

**Comment by CyberAP** [comment]
@CSchulz I do not own a server and can't tell you exact numbers, I only do moderation. But it's approximately 2,2 Ts for 1 D. Owner changed balance a few times because it was disbalanced and now it's perfect, for me at least.

**Comment by Joschasa** [comment]
I don't think, that the balance is really that much off. Traitors just have to play more sneaky, if there are less of them. Adjust your playstyle. Use your arsenal in a clever way. Speak with your mates. Set traps and watch your back. See it as a challange and don't go rambo.
Whereas the innocents can't really replace a dead detective, they simply can't access his shop.
(On our server we have a poison dart gun. The poison does 200 damage and can be stopped with a health station. So balancewise the detective is quite important.)

**Comment by Tommy228** [comment]
I added an option to force autoslain players to be innocents
```lua
-- Force autoslain players to be innocents (overrides SelectRoles)
Damagelog.Autoslay_ForceRole = false
```
At this point we can just force them to stay spectators, it's the same thing.
