### ISSUE TITLE
Round selection out of order

### ISSUE THREAD

**Issue by Violat0r** [Tommy228/TTTDamagelogs#146]
When the rounds exceed more than 10 rounds, they come up as out of order in the round selection under Damagelogs. This is happening on version 2.2.2.

**Comment by Tommy228** [comment]
@Joschasa this is related to your changes

**Comment by Joschasa** [comment]
Are you sure?
I think this is caused by the gmod update itself: https://github.com/garrynewman/garrysmod/commit/84d8935344021d70d90704f16e6ff42548ca5797?w=1

**Comment by Tommy228** [comment]
oh, nvm then

**Comment by Tommy228** [comment]
Fixed in exp
