### ISSUE TITLE
null entity bug, probably due to latest gmod update

### ISSUE THREAD

**Issue by ZachPL** [Tommy228/TTTDamagelogs#148]
[ERROR] lua/damagelogs/sv_rdm_manager.lua:183: Tried to use a NULL entity!
  1. GetNWBool - [C]:-1
   2. func - lua/damagelogs/sv_rdm_manager.lua:183
    3. unknown - lua/includes/modules/net.lua:32

Completely crashed the server.
I wouldnt worry about this, hopefully the hotfix comes out.

**Comment by Tommy228** [comment]
Yeah, they broke GetNW* stuff.. But I think it's fixed with the new gmod update, let me know.

**Comment by Tommy228** [comment]
Should be fixed
