### ISSUE TITLE
Colors are still broken

### ISSUE THREAD

**Issue by Violat0r** [Tommy228/TTTDamagelogs#149]
"Currently highlighted players: none" under Damagelogs is barely viable. Also "Show innocent players" is hard to for roles. Same goes for the controls while watching a death scene.

Under damagelog tab when clicking roles, the alive column no longer has any color at all.

Under the shot logs, the colors will rotate in colors when clicking refresh over and over. Same problem exists under old logs when right clicking and selecting show damage logs over and over.

Not 100% on this one but under old logs I am pretty sure there use to be some colors inside player information such as role.

Running 2.2.2.

**Comment by Joschasa** [comment]
I think we have to revert 5facf4fb75139299327d395979c78845ca68c708 and wait for the gmod update to push https://github.com/garrynewman/garrysmod/commit/ea55c2c939c102a605f26ac6a2bbcb724f5961c1 (or you fix it manually on your server for now)

**Comment by Joschasa** [comment]
The update was just released. (Sadly, gmod still crashes on start with linux -.-)

**Comment by ZachPL** [comment]
Yeah, it needs to be rolled back with the new update.

**Comment by Violat0r** [comment]
Yeah new update broke all the colors. +1 on the roll back.

**Comment by Violat0r** [comment]
@Joschasa I had a similar issue with gmod crashing on start up last week. Try validating TF2.

**Comment by Tommy228** [comment]
Okay I reverted 5facf4f. It should be working now.
