### ISSUE TITLE
Vanishing Weapons

### ISSUE THREAD

**Issue by Lordhallo** [Tommy228/TTTDamagelogs#150]
When having the newest Damagelog Version installed the weapon's in an inventory turn invisible after a little while. I checked all Addon's on my server.

**Comment by Tommy228** [comment]
Should be fixed in this new gmod update, let me know about that too. If it still isn't fixed I'll have to replace all the NW* stuff with net.

**Comment by Lordhallo** [comment]
Fixed

**Comment by HarryTurpin** [comment]
I'm still having this issue after update.

**Comment by Tommy228** [comment]
I need someone to add me on steam. I can run some tests with *sv_allowcslua* and try to figure it out.

**Comment by HarryTurpin** [comment]
http://steamcommunity.com/profiles/76561198041855962/ Feel free.

**Comment by Tommy228** [comment]
It seems to be caused by Set/GetNWInt. I replaced them.
