### ISSUE TITLE
Attempt to call local 'death_reason' (a string value)

### ISSUE THREAD

**Issue by ironer1** [Tommy228/TTTDamagelogs#152]
[ERROR] addons/tttdamagelogs-master/lua/damagelogs/cl_damagelog.lua:187: attempt to call local 'death_reason' (a string value)
  1. func - addons/tttdamagelogs-master/lua/damagelogs/cl_damagelog.lua:187
   2. unknown - lua/includes/modules/net.lua:32

**Comment by Tommy228** [comment]
Fixed in exp
