### ISSUE TITLE
 [ERROR] addons/tttdamagelogs-master/lua/damagelogs/damagelog_events/misc.lua:28: Tried to use a NULL entity!

### ISSUE THREAD

**Issue by ironer1** [Tommy228/TTTDamagelogs#153]
[ERROR] addons/tttdamagelogs-master/lua/damagelogs/damagelog_events/misc.lua:28: Tried to use a NULL entity!
  1. old_func - [C]:-1
   2. SetNWBool - addons/tttdamagelogs-master/lua/damagelogs/damagelog_events/misc.lua:28
    3. unknown - addons/tttdamagelogs-master/lua/damagelogs/ulx/sv_autoslay.lua:165

**Comment by Tommy228** [comment]
Fixed in exp
