### ISSUE TITLE
[ERROR] addons/tttdamagelogs/lua/damagelogs/cl_damagelog.lua:137: bad argument #1 to 'IsKeyDown' (number expected, got nil)

### ISSUE THREAD

**Issue by souplauncher** [Tommy228/TTTDamagelogs#154]
[ERROR] addons/tttdamagelogs/lua/damagelogs/cl_damagelog.lua:137: bad argument #1 to 'IsKeyDown' (number expected, got nil)
  1. IsKeyDown - [C]:-1
   2. Think - addons/tttdamagelogs/lua/damagelogs/cl_damagelog.lua:137
    3. fn - addons/tttdamagelogs/lua/damagelogs/cl_damagelog.lua:155
     4. unknown - addons/ulib/lua/ulib/shared/hook.lua:179

**Comment by Tommy228** [comment]
Show me your config file. The problem is there.

**Comment by souplauncher** [comment]
I found the issue after checking the config. Thank you.

**Comment by sirlenopow** [comment]
same issue for me http://pastebin.com/ViZ8T9Yy
