### ISSUE TITLE
damagelog menu slaying wrong player

### ISSUE THREAD

**Issue by ZachPL** [Tommy228/TTTDamagelogs#156]
http://cloud-4.steamusercontent.com/ugc/711906452538933251/60BBCA4E4DDDD229DA70E425B011F1CE958DCD48/

According to this picture blue reported aaron but porker was slain.

When I asked the admin what happened he said that it said porker when he slayed but then changed to aaron.

The damagelogs also confirm it was aaron not porker, this is a bug with the most recent update.

**Comment by Tommy228** [comment]
This is weird.. does it happen very often?

**Comment by ZachPL** [comment]
I've only seen it happen once

**Comment by Tommy228** [comment]
Well uhm I couldn't reproduce it, it's probably caused by a very rare situation. Reopen if it happens again

**Comment by Herover** [comment]
I've had this happen when the reported player leave, and a admin then slay him. Sometimes it just makes a error but sometimes it also slay the victim.
