### ISSUE TITLE
Rdm manager tab

### ISSUE THREAD

**Issue by WillyMammoth** [Tommy228/TTTDamagelogs#157]
Hello, everytime somone clicks f8 to open the damagelogs, they can't see the Rdm Manager Tab. Also  an error pops up saying "Something is creating script errors" . This is the error that is appearing in console.

[ERROR] addons/tttdamagelogs-master/lua/damagelogs/cl_damagelog.lua:117: attempt to call method 'DrawRDMManager' (a nil value)
  1. OpenMenu - addons/tttdamagelogs-master/lua/damagelogs/cl_damagelog.lua:117
   2. Think - addons/tttdamagelogs-master/lua/damagelogs/cl_damagelog.lua:138
    3. fn - addons/tttdamagelogs-master/lua/damagelogs/cl_damagelog.lua:153
     4. unknown - addons/ulib/lua/ulib/shared/hook.lua:105

**Comment by Tommy228** [comment]
Do you have any other error? Maybe when the server starts. Try reinstalling the logs.

**Comment by WillyMammoth** [comment]
On server start up, the error that appears is: 
[ERROR] addons/tttdamagelogs-master/lua/damagelogs/cl_tabs/rdm_manager.lua:511: ')' expected (to close '(' at line 510) near 'surface'
  1. unknown - addons/tttdamagelogs-master/lua/damagelogs/cl_tabs/rdm_manager.lua:0

Then whenever somone clicks f8 to view the damage logs, another error pops up in console: 
[ERROR] addons/tttdamagelogs-master/lua/damagelogs/cl_damagelog.lua:117: attempt to call method 'DrawRDMManager' (a nil value)
  1. OpenMenu - addons/tttdamagelogs-master/lua/damagelogs/cl_damagelog.lua:117
   2. Think - addons/tttdamagelogs-master/lua/damagelogs/cl_damagelog.lua:138
    3. fn - addons/tttdamagelogs-master/lua/damagelogs/cl_damagelog.lua:153
     4. unknown - addons/ulib/lua/ulib/shared/hook.lua:105

**Comment by Tommy228** [comment]
Looks like you have a bad *cl_tabs/rdm_manager.lua* file. The one on github is fine, you edited it or something.
