### ISSUE TITLE
Previous reports don't work

### ISSUE THREAD

**Issue by CyberAP** [Tommy228/TTTDamagelogs#162]
I am wondering how do previous reports work? On my server the way it worked some time ago was that it showed reports from previous maps only if someone has answered it on the current map. But since 2.1 or something even that is impossible. You can't manage reports from the last round because you don't have enough time and players can't respond to reports because of the same reason. And when the map changes there is no popup to leave a reply, and of course no report at all.

So how exactly do previous reports work? I thought they should store all the reports from previous map during the current map and then erase these reports on a map change. And do the same operation every map. But instead 'previous reports' tab is always empty. In fact most of the reports in last round never get to be managed because there is a lack of time and no reports storage.

**Comment by smallo92** [comment]
Yeah I am having a similar issue. It appears since the latest update that logs are not being saved correctly. I can only see the logs live during a round. But as soon as it's over they are gone for good.

**Comment by CyberAP** [comment]
@smallo92 well that may be another issue, because in my case it all breaks when the map changes and has nothing to do with rounds.

**Comment by smallo92** [comment]
Sorry I may have poorly worded mine. mine fails after a map change too.

**Comment by Tommy228** [comment]
Alright, I'll look into this. It seems to be a SQL issue.

**Comment by smallo92** [comment]
I am using SQLite

**Comment by Tommy228** [comment]
Previous reports work on my server. But I think I'll move them to use .txt files instead of SQL.
