### ISSUE TITLE
Log healthstation

### ISSUE THREAD

**Issue by CyberAP** [Tommy228/TTTDamagelogs#165]
There's a new TTT hook: TTTPlayerUsedHealthStation, maybe we can make use of it in damagelogs?

**Comment by Tommy228** [comment]
Would it be really useful?

**Comment by ZachPL** [comment]
I know on many servers including mine destroying healthstations is considered traitorous, so it could be helpful dealing with random innos who do it for fun.

**Comment by CyberAP** [comment]
Yeah, sometimes people say "I heard gunshots, healing, but no bodies were identified. So I killed you." something like that. It would be useful to know who actually healed.
Or if detective made a freedamage and then placed a healthstation we would know that he helped and the person was healed.

BTW, good idea from @ZachPL, but I don't think that that hook provides that information. This also will be very useful anyway.

**Comment by Tommy228** [comment]
Alright, I'll look into this for 2.4

**Comment by Linkfan123** [comment]
+1

**Comment by Tommy228** [comment]
Done for the next version.
