### ISSUE TITLE
TTT Radio Got Nil

### ISSUE THREAD

**Issue by Violat0r** [Tommy228/TTTDamagelogs#176]
I am getting this error when I have the filter set to show radio commands in logs and when someone uses a radio. This is running the newest github pull.

[ERROR] addons/tttdamagelogs-master/lua/damagelogs/damagelog_events/ttt_radio.lua:51: bad argument #1 to 'GetNameParam' (string expected, got nil)
  1. GetNameParam - [C]:-1
   2. ToString - addons/tttdamagelogs-master/lua/damagelogs/damagelog_events/ttt_radio.lua:51
    3. AddLogsLine - addons/tttdamagelogs-master/lua/damagelogs/cl_listview.lua:87
     4. SetListViewTable - addons/tttdamagelogs-master/lua/damagelogs/cl_listview.lua:117
      5. FinishedLoading - addons/tttdamagelogs-master/lua/damagelogs/cl_tabs/damagetab.lua:396
       6. ReceiveLogs - addons/tttdamagelogs-master/lua/damagelogs/cl_tabs/damagetab.lua:379
        7. func - addons/tttdamagelogs-master/lua/damagelogs/cl_tabs/damagetab.lua:390
         8. unknown - lua/includes/modules/net.lua:32

**Comment by Tommy228** [comment]
Fixed in dev
