### ISSUE TITLE
Current Round Number

### ISSUE THREAD

**Issue by Violat0r** [Tommy228/TTTDamagelogs#182]
This is an enhancement request.

Under the damagelog tab round selection states current round. I always need to bring up the other rounds by clicking on the pull down just to see what the current round is (ie 1 2 3 4...). I need to match it up with rdm manager time to time to see how old the reports are and if action is needed or if the report is too old. I suggest adding adding the round number and making it something like Current Round 2. This will help my server manage rdms more efficiently.

Thanks.

**Comment by Linkfan123** [comment]
+1
[NOOBIE QUESTION ALERT] Maybe you could add the round number to the reports. Or does that already happen?
P.S. You have a server? What is it?

**Comment by Tommy228** [comment]
Done for the next version.
