### ISSUE TITLE
Rounds Missing

### ISSUE THREAD

**Issue by Violat0r** [Tommy228/TTTDamagelogs#184]
After around 10, round 1,2,3...go missing.

Example current round is 11, round 1 goes missing.

I believe this is a bug introduced with #146

**Comment by Joschasa** [comment]
This is intended behaviour: 
https://github.com/Tommy228/TTTDamagelogs/blob/master/lua/damagelogs/cl_tabs/damagetab.lua#L307

**Comment by Violat0r** [comment]
That makes it difficult to review old reports and check for mass rdmers. :/

**Comment by iSnipeu** [comment]
Sounds like a bad fix, instead it should be changed to use numerical sorting (it is sorted alphabetically by default).

**Comment by Linkfan123** [comment]
@iSnipeu I didn't know it did alphabetically.
How? I don't get it.
@Violat0r I get your point.
Here's a suggestion: There could be a feature where it can show you how many times players do infractions and what rounds they have RDM'd in. If Jimmy did 2 infractions with lots of round-space between them, and Dan did 5 infractions with one every round for five rounds, who do you think is more suited to get banned? If you picked Dan, have an imaginary cookie.

**Comment by iSnipeu** [comment]
@Linkfan 123
It's a guess based on a comment from the linked issue near the start of
this one.
https://github.com/Tommy228/TTTDamagelogs/issues/146#issuecomment-80725312

**Comment by Violat0r** [comment]
Yeah like I said it looks like it was a quick fix for #146 but I think we can do better.

**Comment by Linkfan123** [comment]
Where can I make a suggestion? Or is that even a feature?

**Comment by Tommy228** [comment]
@Violat0r what did you mean by "we can do better?". I don't see what needs to be changed here

**Comment by Violat0r** [comment]
@Tommy228 I mean all the rounds should be shown and in order not just the ones in the past 10 rounds.

**Comment by Violat0r** [comment]
I thought of a simple fix for this problem. Just make it Round 01 Rounds 02...Round 11, that way they will all show and be in order.

**Comment by Violat0r** [comment]
Well after deleting lines 307-309 in damagetab.lua everything works perfectly. Rounds are in order even after 10+ rounds.

**Comment by Tommy228** [comment]
Fixed.
