### ISSUE TITLE
Auto Slay People With Many Reports

### ISSUE THREAD

**Issue by Violat0r** [Tommy228/TTTDamagelogs#186]
I have noticed that when people mass rdm, they usually end up killing some traitors. If this is the case they are normally innocent and will not get karma banned right away. This normally leads to them being able to kill 6 people or more.

What I propose is to add a system where if a player gets more than a certain amount of reports in a round, say like 3 reports, RDM manager auto slays them. There also should be an option in the config file to set the amount of reports in a round before it auto slays.

**Comment by drexplosionpd** [comment]
I feel as if this would be abused, Players would more than likely just team up and report people they don't like. If this was implemented I would love a config to also turn it off as a whole (possibly just setting the value of the "amount of reports before slay" to -1?)

**Comment by Violat0r** [comment]
I do believe we can prevent abuse. We just need to verify that the person reporting was in fact killed by the person they are reporting.

**Comment by drexplosionpd** [comment]
That is very true, as long as there would be something in the config to turn off this feature, then i would be all for adding it.

**Comment by Linkfan123** [comment]
+1
If more than a thrid of the server reports, auto-slay.
That's my idea.

**Comment by ZachPL** [comment]
Yeah  to be honest I wouldn't trust my playerbase with this.

**Comment by drexplosionpd** [comment]
They wouldn't do anything but false report and gang up and individuals to get them slain... Thats why if this suggestion gets added it has to have a feature to turn it off... and I feel as if it should be turned off by default.

**Comment by Linkfan123** [comment]
@drexplosionpd That makes sense.
Changing +1 to +0.5

**Comment by Tommy228** [comment]
I agree with @ZachPL and @drexplosionpd, it would end up with a lot of abuse even if I could "try" to detect if it was indeed rdm or not
