### ISSUE TITLE
Suggestion: Mass Report Viewer

### ISSUE THREAD

**Issue by Linkfan123** [Tommy228/TTTDamagelogs#187]
In a tab in the F8 menu, there could be a feature where you could see all the reports made targeting a person. It will show when the report was made, who made it, and the contents of the report. It will also show the response and if the response made the author of the report revoke the report or not.
TL;DR - Make a tab where all the reports can be viewed.

If there is already one, my mistake, I haven't used the RDM Manager in administration before. But if there isn't, it would be cool to have one.

What do you guys think?

**Comment by Violat0r** [comment]
There already is a tab to view reports and pretty much everything you said.

**Comment by Linkfan123** [comment]
Ok, thanks.
Again, haven't used this in administration before.
I'm not sure if I want to close it yet, so I'm going to keep it open for a while.
Thanks again!

**Comment by Linkfan123** [comment]
Closing now.
