### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by npd1124** [Tommy228/TTTDamagelogs#193]
In my log files I am getting these errors

[ERROR] gamemodes/terrortown/gamemode/player.lua:685: Tried to use a NULL entity!
  1. Send - [C]:-1
   2. unknown - gamemodes/terrortown/gamemode/player.lua:685
    3. FireBullets - [C]:-1
     4. ShootBullet - gamemodes/terrortown/entities/weapons/weapon_tttbase.lua:318
      5. PrimaryAttack - gamemodes/terrortown/entities/weapons/weapon_tttbase.lua:242
       6. PrimaryAttack - addons/damagelogs/lua/damagelogs/sv_damageinfos.lua:46
        7. DyingShot - gamemodes/terrortown/entities/weapons/weapon_tttbase.lua:509
         8. unknown - gamemodes/terrortown/gamemode/player.lua:585
          9. FireBullets - [C]:-1
           10. ShootBullet - gamemodes/terrortown/entities/weapons/weapon_tttbase.lua:318
            11. PrimaryAttack - gamemodes/terrortown/entities/weapons/weapon_tttbase.lua:242
             12. unknown - addons/damagelogs/lua/damagelogs/sv_damageinfos.lua:46

L 06/01/2015 - 12:32:36: Lua Error: 
[ERROR] gamemodes/terrortown/gamemode/player.lua:685: Tried to use a NULL entity!
  1. Send - [C]:-1
   2. unknown - gamemodes/terrortown/gamemode/player.lua:685
    3. FireBullets - [C]:-1
     4. ShootBullet - gamemodes/terrortown/entities/weapons/weapon_tttbase.lua:318
      5. PrimaryAttack - gamemodes/terrortown/entities/weapons/weapon_tttbase.lua:242
       6. unknown - addons/damagelogs/lua/damagelogs/sv_damageinfos.lua:46

**Comment by Joschasa** [comment]
Apply this patch:

https://github.com/garrynewman/garrysmod/commit/6ebf85ecaad7560697ab70c72d2a4497f4897f11
