### ISSUE TITLE
Gamemode

### ISSUE THREAD

**Issue by DutchPatrick** [Tommy228/TTTDamagelogs#196]
Could this work on Jailbreak?

**Comment by Linkfan123** [comment]
This is *TTT*Damagelogs.
It should not work with Jailbreak by default.
If you are good at codding, fork it and make your own "JailbrakDamagelogs".
If not, grab a buddy and work on it together or learn Lua. Visual Studio Community has a Lua pluggin so you can program efficiently in Lua *and* C# *and* C++ *and* any other Visual language at the same time! Or you can use Notepad++. Whateves.
