### ISSUE TITLE
aslay ignores ulx immunity when using steamid 

### ISSUE THREAD

**Issue by ZachPL** [Tommy228/TTTDamagelogs#206]
I'm not really sure if this would be consided a bug or not, but it does happen. If you have a usergroup where one shouldn't be able to target the other usergroup, they can just input your steamid and be able to slay you the next round.

**Comment by MrUnknownGamer** [comment]
This is probably something with the ULX System. I know if have CC ULX Commands. The !dban allows you to ban people who are a higher rank then you.

**Comment by Linkfan123** [comment]
!dban? CC ULX?
Arhgg, I'm more confused now than when I started out.
1. How is that not OP?
2. What is CC ULX? An ULX addon?
3. What else is in CC?

**Comment by MrUnknownGamer** [comment]
Ulx custom commands. Just extra commands for ulx.
