### ISSUE TITLE
Chat window client side exit handling

### ISSUE THREAD

**Issue by Trontor** [Tommy228/TTTDamagelogs#217]
I'm really loving this new chat system. Great effort and dedication <3.

There needs to be a way to force the chat window open on a player or at least an indication as to whether or not the player has closed the chat, as I cannot gauge whether a person is typing a long reply or just X'd out of it. 

A simple message when the user clicks out of it is sufficient, maybe then it can remove them from the chat and they can show up in the 'Add players' menu again.

This being said, this chat system is so much better than the default.

Once again, love the work put into this update.

**Comment by Tommy228** [comment]
Done for the next version.

**Comment by Trontor** [comment]
Jul 10, 2015 LOL

**Comment by Tommy228** [comment]
Well I have stopped working on this for 2 years ;)
