### ISSUE TITLE
Players Can Pre-Round Kill

### ISSUE THREAD

**Issue by eGolono** [Tommy228/TTTDamagelogs#229]
I've recently installed the latest version of this mod and since then, players are able to kill each other during the pre-round and the status button doesn't do anything when clicked other than turning blue if clicked while having a report highlighted. Here are the errors:

addons/doglogs_new/lua/damagelogs/cl_tabs/rdm_manager.lua:489: attempt to call upvalue 'status' (a table value)
  1. DrawStatusMenuOption - addons/doglogs_new/lua/damagelogs/cl_tabs/rdm_manager.lua:489
   2. DoClick - addons/doglogs_new/lua/damagelogs/cl_tabs/rdm_manager.lua:549
    3. unknown - lua/vgui/dlabel.lua:218

[ERROR] lua/includes/extensions/math.lua:188: attempt to perform arithmetic on local 'num' (a nil value)
  1. Round - lua/includes/extensions/math.lua:188
   2. unknown - addons/doglogs_new/lua/damagelogs/damagelog_events/damages.lua:43
    3. fn - addons/doglogs_new/lua/damagelogs/sh_events.lua:55
     4. unknown - addons/ulib/lua/ulib/shared/hook.lua:179
      5. FireBullets - [C]:-1
       6. ShootBullet - gamemodes/terrortown/entities/weapons/weapon_tttbase.lua:318
        7. PrimaryAttack - gamemodes/terrortown/entities/weapons/weapon_tttbase.lua:242
         8. unknown - addons/doglogs_new/lua/damagelogs/sv_damageinfos.lua:46

**Comment by Tommy228** [comment]
Update again, this bug has been fixed.

**Comment by eGolono** [comment]
It works great after updating, thanks!
