### ISSUE TITLE
set status error

### ISSUE THREAD

**Issue by Jevon78** [Tommy228/TTTDamagelogs#235]
Hey the set status box isn't working i press the button and it doesn't open the drop down menu 

i have completely reinstalled the addon and it still doesn't work but it prints the error below in console when i press it 
![screenshot 2015-08-28 16 47 04](https://cloud.githubusercontent.com/assets/14018323/9550653/74f0c90c-4da4-11e5-8011-61633d5f328c.png)

**Comment by CSchulz** [comment]
Which status has your report if you do that?

**Comment by Jevon78** [comment]
i can't set the status, it will be what ever it was left on 

Waiting, Canceled by Victim

**Comment by CSchulz** [comment]
Please upload the content of sh_rdm_manager.lua and the status variable in rdm_manager.lua (around line 57)

**Comment by Jevon78** [comment]
its just the default files from the newest version

**Comment by Jevon78** [comment]
sh_rdm_manager
RDM_MANAGER_WAITING_FOR_ATTACKER = 1
RDM_MANAGER_WAITING_FOR_VICTIM = 2
RDM_MANAGER_WAITING = 3
RDM_MANAGER_PROGRESS = 4
RDM_MANAGER_FINISHED = 5
RDM_MANAGER_CANCELED = 6

rdm_manager

local status = {
	[RDM_MANAGER_WAITING_FOR_ATTACKER] = "Waiting for reported player",
	[RDM_MANAGER_WAITING_FOR_VICTIM] = "Waiting for victim",
	[RDM_MANAGER_WAITING] = "Waiting",
	[RDM_MANAGER_PROGRESS] = "In progress",
	[RDM_MANAGER_FINISHED] = "Finished",
	[RDM_MANAGER_CANCELED] = "Canceled by the victim"
}

**Comment by Jevon78** [comment]
but if i go to the lua error line 489 this function is there

local function DrawStatusMenuOption(id)
	menu:AddOption(status(id), function()
		net.Start("DL_UpdateStatus")
		net.WriteUInt(Damagelog.SelectedReport.previous and 1 or 0, 1)
		net.WriteUInt(Damagelog.SelectedReport.index, 16)
		net.WriteUInt(k, 4)
		net.SendToServer()
	end):SetImage(icons[id])
end

**Comment by j03l** [comment]
We are also having this issue, a commit was recently made to change how the status button works. Perhaps this was implemented incorrectly? We have had to downgrade back to 2.3.0 because we cant set reports to 'in progress' unless the reported player replys.

**Comment by CSchulz** [comment]
That is part of the workflow. You should not start with the reports til both sides have answered. Otherwise you would overwrite the current state and can't see if you waiting for the victim or the reported player.

Tell me if you have a better idea for a workflow.

**Comment by Jevon78** [comment]
i cannot set status at all even when the reported player has replied

**Comment by Jevon78** [comment]
ok i just ran the oldest 2.4.0 on my test server and it worked fine so i have put that one on my actual server

**Comment by CSchulz** [comment]
Can not reproduce it at all.

**Comment by j03l** [comment]
The reason we would have our users set reports in progress before they are answered to was because it made it easy for our staff to manage all the reports that were coming in. With this update It also made it impossible staff to resolve a report after map change.
