### ISSUE TITLE
Death Scene Floating Men

### ISSUE THREAD

**Issue by Jevon78** [Tommy228/TTTDamagelogs#236]
Hey i couldn't find a bug post or a fix for this but some of my staff including me are having problems with death scene all the men are floating and move up and down with your mouse. this only happens to some people 

http://images.akamai.steamusercontent.com/ugc/429321685578490136/2F5E6D940622AF4F10A945DEC0CEBACBB12FDD98/  

http://images.akamai.steamusercontent.com/ugc/429321685578489420/CFC7B0CA95D7E4F37729477FA12AB631F798D0B0/

does anyone know any addons that may break the death scene

**Comment by MrUnknownGamer** [comment]
This an error that is found with minecraft maps.

It has already been addressed. Someone please close this

**Comment by Jevon78** [comment]
is there any way to fix it?

**Comment by MrUnknownGamer** [comment]
Possibly but I doubt we will since it'll be a pain in the ass.

**Comment by CSchulz** [comment]
Hum ... I have never seen that. We are playing minecraft_b5 too.

**Comment by Jevon78** [comment]
its fine for some people that the wierd thing so im thinking its something in the client files not server there is only one folder in the Gmod dir and it is the settings

**Comment by Violat0r** [comment]
This can be fixed by changing your video settings. Set water detail to simple reflections.

**Comment by Jevon78** [comment]
Violat0r comment has fixed the issue
