### ISSUE TITLE
error constant

### ISSUE THREAD

**Issue by matiasg90** [Tommy228/TTTDamagelogs#237]
[ERROR] addons/tttdamagelogsnew/lua/damagelogs/damagelog_events/damages.lua:86: attempt to compare number with nil
1. ToString - addons/tttdamagelogsnew/lua/damagelogs/damagelog_events/damages.lua:86
   1. AddLogsLine - addons/tttdamagelogsnew/lua/damagelogs/cl_listview.lua:96
   2. SetListViewTable - addons/tttdamagelogsnew/lua/damagelogs/cl_listview.lua:126
      1. UpdateReportTexts - addons/tttdamagelogsnew/lua/damagelogs/cl_tabs/rdm_manager.lua:715
      2. OnRowSelected - addons/tttdamagelogsnew/lua/damagelogs/cl_tabs/rdm_manager.lua:411
      3. OnClickLine - lua/vgui/dlistview.lua:497
      4. unknown - lua/vgui/dlistview_line.lua:93

**Comment by CSchulz** [comment]
How often occurs this error?
