### ISSUE TITLE
MySQL Issue

### ISSUE THREAD

**Issue by mrvideofreak2010** [Tommy228/TTTDamagelogs#238]
On my website I get the following issue: Fatal error: Call to a member function fetch_assoc() on a non-object in public_html/logs/index.php on line 53

Can you please add me on steam so I can send you some private stuff about my DBs.

**Comment by MrUnknownGamer** [comment]
Or you can let us fix it without your db stuff

**Comment by mrvideofreak2010** [comment]
I've also tried changing my DB Host to my server's ip and I get this error: MySQL connection failed:
Can't connect to MySQL server on '185.38.151.164' (110)

**Comment by CSchulz** [comment]
If the mysql configuration correct, it seems that your MySQL isn't running or something is blocking the communication.

**Comment by mrvideofreak2010** [comment]
I host both my website and server with Nitrous Networks

**Comment by mrvideofreak2010** [comment]
Help please?

**Comment by MaZyGer** [comment]
I had the same error. But I know why I got it.

You receive this error if your addon did not create tables in your database. So if you didn't restart your server just do it and check if their is tables after the restart. Then your website should work.

Its little bit old but maybe you didn't still figure out but hope it helps.

**Comment by CSchulz** [comment]
Did you use the ip shown in the cPanel of Nitrous Networks?
Did you added a custom database?

**Comment by MaZyGer** [comment]
@CSchulz 
Are you asking me? If yes I do not use Nitrous Networks. I have a dedicated server.
I am using nginx instead of apache.
Also I am using MariaDB instead of MySQL but everything works perfectly.

**Comment by CSchulz** [comment]
No, it was for @mrvideofreak2010

**Comment by EstevanTH** [comment]
As I could read, the PHP script is not protected against failed MySQL connections. That should be fixed by anybody.
