### ISSUE TITLE
Set Status System

### ISSUE THREAD

**Issue by Violat0r** [Tommy228/TTTDamagelogs#239]
Setting the status of reports have recently been changed in the past few months. Now you must set a report in progress before you can set it to finished. I have been getting a lot of complaints from my admins that it is create extra work for them. It is also an annoyance that we must wait for a victim to respond even though they have left the server so we cannot set the status at all.

I recommend going back to the old way of setting status. It was easy and faster without many issues.

**Comment by CSchulz** [comment]
What kind of issues do you have besides the waiting for victim and the different workflow?

**Comment by Violat0r** [comment]
Well it takes a lot more work to be honest. Lets say there is 4 reports that need to be dealt with. It takes double the amount of mouse clicks to finish a report. 

Set Status > In Progress > Set Status > Finished

instead of

Set Status > Finished

On my server there is a lot of rdm so it is creating a lot more work for the admins just to deal with reports. A lot of these reports it is clear they are rdm or just a false report. So you are looking at a lot more clicks and time wasted just to wait for a response from players when you know it is a false report or clearly rdm and what not.

**Comment by CSchulz** [comment]
@Linkfan123 "In progress" normally should be set if an op is taking the report to prevent duplicate work on one report.

**Comment by OHQSaucey** [comment]
I would really like this old system to come back as well, I do not like having to set things to "in progress".

**Comment by Tommy228** [comment]
The old system will come back in the next version.
