### ISSUE TITLE
Web error after 1/19/16 gmod update 

### ISSUE THREAD

**Issue by ZachPL** [Tommy228/TTTDamagelogs#242]
http://imgur.com/xbxvM2L

This started happening right after the most recent gmod updates where it sometimes will append the steamid to the end and not show the names of players.

I checked and my damagelogs are fine before tuesday and this started happening afterwords.

http://assets-1.joinsg.net/tttdamage/index.php?static&round_list=21021&map_loaded_list=21018_21021&day_list=2016_1_19&month_list=2016_1&year_list=2016

Anyone having this issue and fixed this already?

**Comment by comedinha** [comment]
http://200.6.36.127/dmglog/index.php?static&round_list=20953&map_loaded_list=20945_20953&day_list=2016_1_22&month_list=2016_1&year_list=2016
Same error

**Comment by ZachPL** [comment]
This week's patch notes

util.TableToJSON handles arrays properly

Pretty sure it has something to do with that

**Comment by ZachPL** [comment]
@EstevanTH Any chance you could retake a look at this.

**Comment by comedinha** [comment]
Neutron have same problem... http://i.imgur.com/Fy1iDri.png

**Comment by ZachPL** [comment]
interesting, let me know if a fix comes out for it so I can cross reference, I dont have access to that script currently.

I pulled the decoded json from php and it looks right... but i'm not sure what it looked like before the update and have no way to look.

I have next to 0 experience with json and php so im struggling through it

**Comment by EstevanTH** [comment]
Hello,
I totally forgot this PHP script. :flushed:
I have no TTT server so I can try nothing. Having an piece of database would be handy.
I rather think that the problem comes from Garry's Mod, so the contents of the database is corrupted.

**Comment by CSchulz** [comment]
It would be easy to fix the PHP script, but I think the old logs are lost without any migration to the "new" format.

**Comment by EstevanTH** [comment]
I think that the script does not decode valid information while doing
```php
$round_info['damagelog'] = json_decode($round_info['damagelog'], true);
```
in [website_code/index.php at line 453](https://github.com/Tommy228/TTTDamagelogs/blob/master/website_code/index.php#L453)

**Comment by zhulb001** [comment]
@EstevanTH I'm not sure if this helps at all

I put this in a file
$round_info['damagelog'] = json_decode($round_info['damagelog'], true);
echo var_dump($round_info['damagelog']), '<br>'; 

which displays this
http://assets.joinsg.net/tttdamage/event.php

Are you able to tell if that is correct or not?

**Comment by ZachPL** [comment]
@EstevanTH I'm not sure if this helps at all

I put this in a file
$round_info['damagelog'] = json_decode($round_info['damagelog'], true);
echo var_dump($round_info['damagelog']), '
';

which displays this
http://assets.joinsg.net/tttdamage/event.php

Are you able to tell if that is correct or not?

**Comment by EstevanTH** [comment]
Can I see the damagelog page for the date you chose to display in your link?

**Comment by ZachPL** [comment]
Here is the link

http://assets.joinsg.net/tttdamage/index.php?static&round_list=22241&map_loaded_list=22234_22241&day_list=2016_1_24&month_list=2016_1&year_list=2016

its round 8 4:26 am  tttminecraft_mythic_sg_b9 (3:58 AM) on the 24 of january 2016

**Comment by EstevanTH** [comment]
A failing example:
```php
	[3]=>
		array(5) {
			["round"]=>
			int(8)
			["infos"]=>
			array(9) {
				[0]=>
				string(13) "Unpaid Intern"
				[1]=>
				int(1)
				[2]=>
				string(7) "jwjg672"
				[3]=>
				int(0)
				[4]=>
				int(9)
				[5]=>
				string(14) "weapon_ttt_m16"
				[6]=>
				string(18) "STEAM_0:1:79446472"
				[7]=>
				string(19) "STEAM_0:1:121213779"
				[8]=>
				int(9)
			}
			["id"]=>
			int(1)
			["type"]=>
			string(3) "DMG"
			["time"]=>
			int(60)
		}
```
A working example:
```php
		[4]=>
		array(5) {
			["round"]=>
			int(8)
			["infos"]=>
			array(10) {
				[2]=>
				int(0)
				[5]=>
				int(200)
				[4]=>
				int(0)
				[9]=>
				int(200)
				[8]=>
				string(18) "STEAM_0:0:90066397"
				[3]=>
				string(15) "BlackWolf-TFMV-"
				[7]=>
				string(19) "STEAM_0:1:121213779"
				[1]=>
				string(7) "jwjg672"
				["icon"]=>
				array(1) {
					[0]=>
					string(22) "icon16/exclamation.png"
				}
				[6]=>
				string(15) "weapon_zm_rifle"
			}
			["id"]=>
			int(1)
			["type"]=>
			string(3) "DMG"
			["time"]=>
			int(62)
		}
```

I regret that this happens. I do not remember what the JSON data look like.
 I can't fix by just checking whether the key `0` exists or not.
Can you please capture JSON data before they get decoded at line 413?
```php
$round_info['damagelog'] = json_decode($round_info['damagelog'], true);
```

**Comment by ZachPL** [comment]
@EstevanTH 
http://assets.joinsg.net/tttdamage/event2.php

I believe that is what you are asking for

**Comment by EstevanTH** [comment]
I added tabs and new lines to make the JSON data clean.
```json
{
	"ShootTable":
	{
		"6":[
			[
				"Weegee",
				"weapon_zm_molotov"
			]
		],
		"9":[
			[
				"jwjg672",
				"weapon_zm_revolver"
			]
		],
		"12":[
			[
				"jwjg672",
				"weapon_zm_revolver"
			]
		],
		"13":[
			[
				"jwjg672",
				"weapon_zm_revolver"
			]
		],
		"14":[
			[
				"jwjg672",
				"weapon_zm_revolver"
			]
		],
		"67":[
			[
				"Unpaid Intern",
				"weapon_zm_shotgun"
			]
		],
		"84":[
			[
				"Unpaid Intern",
				"weapon_zm_shotgun"
			]
		],
		"83":[
			[
				"Unpaid Intern",
				"weapon_zm_shotgun"
			]
		],
		"62":[
			[
				"BlackWolf-TFMV-",
				"weapon_zm_rifle"
			]
		],
		"24":[
			[
				"jwjg672",
				"weapon_ttt_m16"
			],
			[
				"jwjg672",
				"weapon_ttt_m16"
			],
			[
				"jwjg672",
				"weapon_ttt_m16"
			]
		],
		"23":[
			[
				"jwjg672",
				"weapon_ttt_m16"
			]
		],
		"60":[
			[
				"jwjg672",
				"weapon_ttt_m16"
			],
			[
				"jwjg672",
				"weapon_ttt_m16"
			],
			[
				"jwjg672",
				"weapon_ttt_m16"
			]
		],
		"57":[
			[
				"jwjg672",
				"weapon_ttt_m16"
			],
			[
				"jwjg672",
				"weapon_ttt_m16"
			],
			[
				"jwjg672",
				"weapon_ttt_m16"
			],
			[
				"jwjg672",
				"weapon_ttt_m16"
			],
			[
				"jwjg672",
				"weapon_ttt_m16"
			]
		],
		"66":[
			[
				"Unpaid Intern",
				"weapon_zm_shotgun"
			]
		],
		"56":[
			[
				"jwjg672",
				"weapon_ttt_m16"
			],
			[
				"jwjg672",
				"weapon_ttt_m16"
			],
			[
				"jwjg672",
				"weapon_ttt_m16"
			],
			[
				"jwjg672",
				"weapon_ttt_m16"
			],
			[
				"jwjg672",
				"weapon_ttt_m16"
			]
		],
		"61":[
			[
				"jwjg672",
				"weapon_ttt_m16"
			]
		],
		"59":[
			[
				"jwjg672",
				"weapon_ttt_m16"
			],
			[
				"jwjg672",
				"weapon_ttt_m16"
			],
			[
				"jwjg672",
				"weapon_ttt_m16"
			],
			[
				"jwjg672",
				"weapon_ttt_m16"
			],
			[
				"jwjg672",
				"weapon_ttt_m16"
			]
		]
	},
	"Infos":
	{
		"BlackWolf-TFMV-":
		{
			"role":0,
			"steamid64":"76561198140000000",
			"steamid":"STEAM_0:1:123456"
		},
		"Unpaid Intern":
		{
			"role":1,
			"steamid64":"76561198140000000",
			"steamid":"STEAM_0:1:123456"
		},
		"Weegee":
		{
			"role":0,
			"steamid64":"76561198140000000",
			"steamid":"STEAM_0:1:123456"
		},
		"jwjg672":
		{
			"role":0,
			"steamid64":"76561198140000000",
			"steamid":"STEAM_0:1:123456"
		}
	},
	"DamageTable":[
		{
			"round":8,
			"infos":[
				"Unpaid Intern",
				1,
				"STEAM_0:1:123456",
				2,
				2
			],
			"id":8,
			"type":"WEP",
			"time":3
		},
		{
			"round":8,
			"infos":[
				"Unpaid Intern",
				1,
				"STEAM_0:1:123456",
				1,
				1
			],
			"id":8,
			"type":"WEP",
			"time":5
		},
		{
			"round":8,
			"infos":[
				"Weegee",
				0,
				"weapon_zm_molotov",
				"STEAM_0:1:123456"
			],
			"id":6,
			"type":"NADE",
			"time":6
		},
		{
			"round":8,
			"infos":[
				"Unpaid Intern",
				1,
				"jwjg672",
				0,
				9,
				"weapon_ttt_m16",
				"STEAM_0:1:123456",
				"STEAM_0:1:123456",
				9
			],
			"id":1,
			"type":"DMG",
			"time":60
		},
		{
			"round":8,
			"infos":
			{
				"2":0,
				"5":200,
				"4":0,
				"9":200,
				"8":"STEAM_0:1:123456",
				"3":"BlackWolf-TFMV-",
				"7":"STEAM_0:1:123456",
				"1":"jwjg672",
				"icon":[
					"icon16/exclamation.png"
				],
				"6":"weapon_zm_rifle"
			},
			"id":1,
			"type":"DMG",
			"time":62
		},
		{
			"round":8,
			"infos":[
				"BlackWolf-TFMV-",
				0,
				"jwjg672",
				0,
				"weapon_zm_rifle",
				"STEAM_0:1:123456",
				"STEAM_0:1:123456",
				73
			],
			"id":4,
			"type":"KILL",
			"time":62
		},
		{
			"round":8,
			"infos":[
				"BlackWolf-TFMV-",
				0,
				"Unpaid Intern",
				1,
				67,
				"weapon_zm_shotgun",
				"STEAM_0:1:123456",
				"STEAM_0:1:123456",
				67
			],
			"id":1,
			"type":"DMG",
			"time":66
		},
		{
			"round":8,
			"infos":[
				"BlackWolf-TFMV-",
				0,
				"Unpaid Intern",
				1,
				55,
				"weapon_zm_shotgun",
				"STEAM_0:1:123456",
				"STEAM_0:1:123456",
				55
			],
			"id":1,
			"type":"DMG",
			"time":67
		},
		{
			"round":8,
			"infos":[
				"Unpaid Intern",
				1,
				"BlackWolf-TFMV-",
				0,
				"weapon_zm_shotgun",
				"STEAM_0:1:123456",
				"STEAM_0:1:123456",
				74
			],
			"id":4,
			"type":"KILL",
			"time":67
		},
		{
			"round":8,
			"infos":
			{
				"2":1,
				"5":"weapon_ttt_flaregun",
				"3":"STEAM_0:1:123456",
				"1":"Unpaid Intern"
			},
			"id":8,
			"type":"WEP",
			"time":75
		},
		{
			"round":8,
			"infos":[
				"Weegee",
				0,
				"Unpaid Intern",
				1,
				55,
				"weapon_zm_shotgun",
				"STEAM_0:1:123456",
				"STEAM_0:1:123456",
				55
			],
			"id":1,
			"type":"DMG",
			"time":83
		},
		{
			"round":8,
			"infos":[
				"Weegee",
				0,
				"Unpaid Intern",
				1,
				78,
				"weapon_zm_shotgun",
				"STEAM_0:1:123456",
				"STEAM_0:1:123456",
				78
			],
			"id":1,
			"type":"DMG",
			"time":84
		},
		{
			"round":8,
			"infos":[
				"Unpaid Intern",
				1,
				"Weegee",
				0,
				"weapon_zm_shotgun",
				"STEAM_0:1:123456",
				"STEAM_0:1:123456",
				75
			],
			"id":4,
			"type":"KILL",
			"time":84
		}
	]
}
```

I need some time to understand what the failure is.

**Comment by EstevanTH** [comment]
Okay, the failure is easy to understand.
In failing DamageTable events, the data are naturally indexed (using an integer key, which is 1 to n in Lua and 0 to n-1 in PHP).
In successing DamageTable events, the data are indexed by a string containing an integer (probably using a integer-to-string key, which was 1 to n in Lua, so it is incorrectly converted in PHP).

When I made the PHP script, everything was probably in the integer-to-string format, that's why only events containing integer-to-string keys are displayed properly.

**Comment by ZachPL** [comment]
So this is just a issue with the PHP script formatting? Any chance you could fix it?

**Comment by Tommy228** [comment]
Can you try now? I have justed updated _sh_events.lua_ efdbd0f

**Comment by ZachPL** [comment]
Yep, that fixed it. At least on the web, i'll check ingame to make sure later tonight.

If only I knew the fix was that easy. Thanks!

**Comment by ZachPL** [comment]
As far as I can tell everything seems good.

**Comment by comedinha** [comment]
Fixed for me
