### ISSUE TITLE
Arrays In Webserver?

### ISSUE THREAD

**Issue by SoarinBolt** [Tommy228/TTTDamagelogs#243]
Hello! I checked my logs and I noticed this:
http://apogcwebsite.site.nfoservers.com/gmodweb/website_code/index.php?static&round_list=99&map_loaded_list=98_99&day_list=2016_2_1&month_list=2016_2&year_list=2016

I fixed one of the issues but the arrays showing is still confusing..

**Comment by EstevanTH** [comment]
Is it about `CRED` lines?
It's simply a way to display events that could not be decoded.
The web script does not know `CRED` entries.

**Comment by Joe-Howanski** [comment]
I think this issue extends into more, I'm seeing it with kills, and damage in general.

Example:
http://gmod.harpoongaming.com/dlogs/index.php?static&round_list=360552&map_loaded_list=360546_360597&day_list=2016_6_10&month_list=2016_6&year_list=2016

**Comment by ZachPL** [comment]
Make sure you do this commit, 

https://github.com/Tommy228/TTTDamagelogs/commit/6fc3ab624ed4e2590f82427159b16cb071f33a0e

And cred, body, and radio are not currently implemented, so the easiest way to not show is to remove the corresponding files.
