### ISSUE TITLE
MySQL error :  SQL Error: near "LIMIT": syntax error

### ISSUE THREAD

**Issue by FVJohnny** [Tommy228/TTTDamagelogs#247]
I get this error like two times each round, and it seems to appear one time for each player like i'll show  you in the attached picture.

I tryed to reinstall and update it, but it doesn't work 
![d54f56e34123b733bd511b2f543c9d61](https://cloud.githubusercontent.com/assets/18448398/14510856/0075f680-01d4-11e6-90b2-4ea70dab4368.png)

**Comment by EstevanTH** [comment]
I guess that you do not know where the error happens in the Lua script.
It's obviously somewhere where you see a `LIMIT` in a string.

**Comment by FVJohnny** [comment]
Its on the ulx module that manages the autoslays, the shared or the server file i cant remember which one of those two

**Comment by EstevanTH** [comment]
I found 3 SQLite requests with a mistake inside.
There are strings with missing quotes. In case of a missing variable or whatever, the request may be corrupted. It may also be dangerous (SQL injection).

[lua/damagelogs/ulx/sv_autoslay.lua at line 36](https://github.com/Tommy228/TTTDamagelogs/blob/master/lua/damagelogs/ulx/sv_autoslay.lua#L36)
```lua
sql.Query("UPDATE damagelog_names SET name = "..sql.SQLStr(name).." WHERE steamid = '"..steamid.."' LIMIT 1;")
```

[lua/damagelogs/ulx/sv_autoslay.lua at line 142](https://github.com/Tommy228/TTTDamagelogs/blob/master/lua/damagelogs/ulx/sv_autoslay.lua#L142)
```lua
sql.Query("UPDATE damagelog_autoslay SET admins = "..sql.SQLStr(util.TableToJSON(new_steamids))..", reason = "..sql.SQLStr(reason)..", time = "..os.time().." WHERE ply = '"..steamid.."' LIMIT 1;")
```

[lua/damagelogs/ulx/sv_autoslay.lua at line 152](https://github.com/Tommy228/TTTDamagelogs/blob/master/lua/damagelogs/ulx/sv_autoslay.lua#L152)
```lua
sql.Query(string.format("UPDATE damagelog_autoslay SET admins = %s, slays = %i, reason = %s, time = %s WHERE ply = '%s' LIMIT 1;", ....... ))
```

**Comment by EstevanTH** [comment]
Sorry, mistake from me: [sql.SQLStr()](https://github.com/garrynewman/garrysmod/blob/master/garrysmod/lua/includes/util/sql.lua#L9) already adds quotes by default!
Damn, this whole escape thing is way more complicated than required...

**Comment by FVJohnny** [comment]
Then what could it be? u.u

**Comment by EstevanTH** [comment]
The escape may not be as safe as it seems. Honestly I see no reason for a failure when reading SQL requests, they need a more advanced inspection.
