### ISSUE TITLE
Ideal Website Conditions For Installing

### ISSUE THREAD

**Issue by lolapples** [Tommy228/TTTDamagelogs#257]
Hi there,
I apologise if this is the wrong area to ask this, but it appears as though your facepunch thread is closed, and I'd like to ask a question. 
This could be considered an issue, not with your side of things, but mine. Every time I put up your website_code onto a vps of mine, one of two things will happen:
It will list the code of index.php, or it will say that the page isn't working, HTTP ERROR 500. 
The one where it lists the code isn't so bad, I figure it's just the wrong version of PHP, and I'm not upgrading it on that VPS because it has important things requiring a earlier version. 
The 2nd one where it gives the HTTP ERROR 500, I cannot figure out why.
I'm using Ubuntu 14.04, Apache2, Mysql and PHP 5.5.38-4+deb.sury.org~trusty+1 (cli)
I've literally uploaded this straight from the download here, not even renamed it. 
http://104.156.233.12/website_code/
Send halp!

**Comment by EstevanTH** [comment]
Hi.
An HTTP 500 is triggered by something. Hence it will add something in the Apache log, by default.
If you copy and paste the lines about that error, I think that you will figure out the answer of the problem.
Maybe it is related to the script, maybe it is related to the web server.

- If you have the beautiful page saying "Internal error", the problem is really probably about configuration. Check the `.htaccess` file and see if all the required Apache modules are loaded.
- If the page is blank or displays details (line of error, etc.) then it's a problem with the PHP script.

Again, check out the Apache log files as it will give you serious clues.

**Comment by NotLarryTheDestroyer** [comment]
[Wed Jan 11 17:29:10.839984 2017] [:error] [pid 29916] [client 108.61.185.177:47360] PHP Fatal error:  Call to a member function fetch_assoc() on a non-object in /home/admin/web/therustycutlass.com/public_html/damagelogs/index.php on line 69
[Wed Jan 11 17:31:02.068645 2017] [core:alert] [pid 31243] [client 108.61.185.177:47366] /home/admin/web/therustycutlass.com/public_html/damagelogs/.htaccess: <Directory not allowed here

Heyo, So i had these errors ^
I added t he website_code, chmodded everything to 755, then wrote a .htaccess with:
<Directory /damagelogs>
Options +Indexes
allow from all
</Directory>
I removed the Directory biz, left those two lines, then it shows the website properly, but just January 1st, 1970

I went through 3 full maps with a bot, it logged damage for each round and I could view them normally during that map. When I load the next map, nothing in old logs, and "Nothing here" in "Last round of previous map".

**Comment by EstevanTH** [comment]
Heya.
You have a problem while opening the database.
Check that the MySQLi extension is loaded and that the MySQL connection parameters are correct.

**Comment by NotLarryTheDestroyer** [comment]
Woah what, my MYSQL server and gmod server are hosted separately. I created the database admin_damagelogs on the web server. Then edited the mysqloo config in the damagelogs folder to reflect the settings. 

Where would I check this extension? On the web server?

**Comment by NotLarryTheDestroyer** [comment]
I ran:
`sudo apt-get install php5-mysql`
and 
`sudo apt-get install php5-mysql`
restarted apache2 and its still at 1970.

**Comment by NotLarryTheDestroyer** [comment]
Bump.
Send halp D;

**Comment by EstevanTH** [comment]
Is the configuration PHP script properly filled with all MySQL information?

**Comment by NotLarryTheDestroyer** [comment]
Yes. Switched between ip and localhost

**Comment by NotLarryTheDestroyer** [comment]
I've just read this error from my donation system (that works regardless)
Neither MySQLoo or tmysql4 module could be loaded!
Could that be a problem?

**Comment by EstevanTH** [comment]
If GMod cannot access the database for some reason then the tables will not be created, so the PHP script will always error. What is wrong with MySQLoo?

**Comment by NotLarryTheDestroyer** [comment]
I just switched from a windows to Linux server so I had the wrong dlls. Also I'd previously had the older versions of Mysqloo and libsteam.so
But now they're updated and still nothing. 
Any particular ports I need open? I open the ones for ssh and the serversaw and close all the rest.
