### ISSUE TITLE
Serverguard

### ISSUE THREAD

**Issue by untrainAssassin** [Tommy228/TTTDamagelogs#260]
This is not an issue this is a request and I don't know where else to put it I was wondering if you can make an auto slay for Serverguard.

**Comment by untrainAssassin** [comment]
As well it's not really compatible with serverguard the RDM manager only recognizes default ulx rank's for serverguard.

**Comment by FusionLord** [comment]
I made a dirty mockup for serverguard support, #261

**Comment by Tommy228** [comment]
I'm going to contact the creator of ServerGuard for a better solution for this.
