### ISSUE TITLE
RDM Report can crash players until 2 map changes 

### ISSUE THREAD

**Issue by LightPrismHD** [Tommy228/TTTDamagelogs#263]
Okay, so a friend of mine found this issue and we found that it works on a lot of GMod TTT servers with this RDM Manager.

If you make a report on somebody, and type in something like "o o f                                     d" or something similar, the reported player's game freezes the instant they receive their report. Basically, when the reported player dies and the report would register to them, something happens that freezes their game and keeps them from being able to relog onto the server until 2 map changes later, where the report disappears from the system. They also have to go through the task manager to close the game, players targeted by this can't even tab out (only CTRL+ALT+DELETE --> arrow keys to highlight the hl2.exe task --> press DEL to close the program). This issue only affects players on the server that the report was sent on.

I tested this multiple times, and it seems to work only when the report is typed a certain way.
"o o f                                      [any words]" works
"b o o                                     [any words]" works
"b o                                        [any words]" works
These formats do not work:
"test                                       [any words]"

So it seems to be something due to the space in-between the first letters (works with 2-3 letters) and a long space between that and any final letter[s] in the report.

I haven't tested this enough to determine what exactly causes this, but I just felt you should know about this. I can try to record a video in-game and submit it as evidence that this works if you guys need it. Just wanted you guys to know that this is a thing, and maybe help out any patch that might be necessary.

EDIT: This thread is removing the mass spaces. this works when there are a lot of spaces in a row (say around 20+ before the '[any words]' place.

**Comment by MinIsMin** [comment]
This seems not to be an issue with TTTDamagelogs but with GarrysMod.
[I created an issue and credited you.](https://github.com/Facepunch/garrysmod-issues/issues/3257)

**Comment by CSchulz** [comment]
I think we should add a workaround f.e.

`string.gsub( text, "%s+", " " )`

**Comment by MinIsMin** [comment]
Should be fixed serverside (clients can crash themselves but not others) with https://github.com/Tommy228/TTTDamagelogs/commit/3533caded7f064c55b90a679d5dee516d729be7b  (see https://github.com/MinIsMin/NotYetTDM/commit/44ffcca98a822fe039e9a317a712a381743ae822 for diff)
