### ISSUE TITLE
[ERROR] lua/includes/extensions/net.lua:182: net.ReadType: Couldn't read type 78

### ISSUE THREAD

**Issue by Santi871** [Tommy228/TTTDamagelogs#276]
`[Doggo|138|STEAM_0:0:86466187] Lua Error:
 
[ERROR] lua/includes/extensions/net.lua:182: net.ReadType: Couldn't read type 78
  1. error - [C]:-1
   2. ReadType - lua/includes/extensions/net.lua:182
    3. ReadType - lua/includes/extensions/net.lua:121
     4. ReadType - lua/includes/extensions/net.lua:124
      5. ReadTable - lua/includes/extensions/net.lua:124
       6. func - addons/tttdamagelogs-master/lua/damagelogs/client/recording.lua:292
        7. unknown - lua/includes/extensions/net.lua:32`

**Comment by iagrib** [comment]
Same happens to me when I try to watch Death Scenes, but instead of 'type 78' it says 'type 65'

**Comment by MrUnknownGamer** [comment]
I've seen these error messages before. Do the numbers equate to the certain type of variable were trying to pass?

**Comment by iViscosity** [comment]
It appears this is happening when too much data is being sent ([similar post]( https://facepunch.com/showthread.php?t=1529558&p=50834454&viewfull=1#post50834454) ). Max a net message can send is 64 KB. 

And @MrUnknownGamer, the error is at [line 292](https://github.com/Tommy228/TTTDamagelogs/blob/master/lua/damagelogs/client/recording.lua#L292), which is a table that is being sent from [server/recording.lua:105](https://github.com/Tommy228/TTTDamagelogs/blob/d6895a0fa4ed48ca71ed8969d2945fdd79e9ac0e/lua/damagelogs/server/recording.lua#L105). 

It seems to me that [Damagelog.Death_Scenes[ID]](https://github.com/Tommy228/TTTDamagelogs/blob/d6895a0fa4ed48ca71ed8969d2945fdd79e9ac0e/lua/damagelogs/server/recording.lua#L98) is writing too much data (> 64 KB) and can't be read by the client. I'll try watching some death scenes when I can today, and see if I can reproduce this.

**Comment by Tommy228** [comment]
I guess it happens on very large servers (> 32 players). I didn't think Damagelog.Death_Scene could be that big... I will try to do some optimizations and see how it goes.

**Comment by Tommy228** [comment]
From what I see, what I was doing before (on the 2.4.0) is compressing the data and sending it using `net.WriteData`. I didn't think it was necessary to do that, but now that this error comes up let's just go back to the old way.

**Comment by Tommy228** [comment]
Fixed in https://github.com/Tommy228/TTTDamagelogs/commit/b5c79ce61f7365206315679d42fb9e44b2d57ab3. Optimizations still have to be done.
