### ISSUE TITLE
Slay command not working and death scenes

### ISSUE THREAD

**Issue by Quinlan102** [Tommy228/TTTDamagelogs#285]
When i slay someone thru the rdm manager this comes up in chat.
also sometimes the death scene does not shows the correct scene or does not work at all

Usage: ulx aslayid <steamid> [<rounds (0 to cancel slay): 0<=x, default 1>] [{slay reason}] - Slays the steamid for a specified

**Comment by Tommy228** [comment]
You are not using the correct version of the addon. Download it from the [releases ](https://github.com/Tommy228/TTTDamagelogs/releases)and not directly from the repo which may contain experimental or untested code.

The Death Scene bug has already been reported (https://github.com/Tommy228/TTTDamagelogs/issues/276), a new update will come in a few days that should fix it along with other known bugs.
