### ISSUE TITLE
Drownings are not counted in logs

### ISSUE THREAD

**Issue by Tommy228** [Tommy228/TTTDamagelogs#286]

**Comment by Junnnneee** [comment]
pretty sure fall damage death too

**Comment by Tommy228** [comment]
Yeah, I'll see what I can do about that this evening. Maybe I will add new events.

**Comment by MinIsMin** [comment]
Fall damage were already fixed.
Drownings now are in a [new event](https://github.com/Tommy228/TTTDamagelogs/commit/c594baa8f6a955e9ff6fb396220c30ad906162cd#diff-05f6b5791331d1a223bf7d9c3e44257c).
