### ISSUE TITLE
AutoForce not working

### ISSUE THREAD

**Issue by megaherox** [Tommy228/TTTDamagelogs#289]
When i slay a player with slaynr the slayed one will not moved to innocent..

**Comment by Tommy228** [comment]
Do you have any addon that may interfere with TTT roles ? Pointshop roles for example.

**Comment by megaherox** [comment]
No , i have Pointshop 2 installed, and with the old 2.7 its working fine

**Comment by Tommy228** [comment]
The parameter for that has changed on the new version, previously it was `Damagelog.Autoslay_ForceRole`, now it's `Damagelog.ULX_Autoslay_ForceRole`, so make sure you are setting the right parameter to true on the configuration file.

**Comment by iViscosity** [comment]
Also be sure you're using aslay and not Bender's slaynr. They're two completely different things.

**Comment by iagrib** [comment]
If you have Pointshop 2 Boosters, uncheck this: https://i.imgur.com/bNnORut.png (Management - DLC Settings - Boosters)
And remove any role chance boosters from the shop if you have any.

If you want to keep these boosters you'll need to override default TTT role logic with a function that both prevents people with slays from getting roles _and_ makes people with boosters more likely to get their role.

**Comment by megaherox** [comment]
Thank you for the create Support (: !
