### ISSUE TITLE
TTT Special Rounds disable RDM Manager reports during rounds

### ISSUE THREAD

**Issue by megaherox** [Tommy228/tttdamagelogs#293]
Hello,
In the Old Damagelogs the command was :

In order to disable RDM Manager reports during rounds where karma & score is unaffected, place this in line 144 of damagelogs/cl_rdm_manager.lua:

-- Start --
if GetGlobalBool( "SpecialRoundsOverrideRDMReport" ) then return end
-- End --

what is the new one ... /: i am not good in lua 

Thanks for your time

**Comment by Junnnneee** [comment]
https://github.com/Tommy228/TTTDamagelogs/blob/master/lua/damagelogs/client/rdm_manager.lua#L237
i found the same function i guess
