### ISSUE TITLE
Error deathsceen

### ISSUE THREAD

**Issue by Justinh4x** [Tommy228/TTTDamagelogs#295]
Hello, I seem to have this error when attempting to view a death scene

Error in hook Think: addons/tttdamagelogs-master/lua/damagelogs/client/recording.lua:581: bad argument #1 to 'SetSequence' (string expected, got nil)
stack traceback:
    [C]: in function 'SetSequence'
    addons/tttdamagelogs-master/lua/damagelogs/client/recording.lua:581: in function 'fn'
    addons/ulib/lua/ulib/shared/hook.lua:109: in function <addons/ulib/lua/ulib/shared/hook.lua:92>
    [C]: in function '‌⁪‎⁭‬⁯‪‭'

[ERROR] 
  1. unknown - [C]:-1

**Comment by Junnnneee** [comment]
#274
