### ISSUE TITLE
Addon just not working

### ISSUE THREAD

**Issue by Monkeys7** [Tommy228/TTTDamagelogs#296]
I have used this addon before and maybe I just forgot how to add this to my server but either way it just isn't working. I am downloading the addon, putting it in the addon folder, editing config file to fit my ulx ranks, syncing my server, and restarting my server and it is not working. In config RDM Manager on is set to true. I just have no idea why it is not working. Any advice?

**Comment by MinIsMin** [comment]
What do you mean by 'not working'?
- Can you open the Damagelogs (default key: F8)?
- Do you see the config menu in the F1 menu?
- Are there any lua errors in the console?

**Comment by Monkeys7** [comment]
I figured it out. But at the time I couldn't open damagelogs with F8 I could not open config menu and there were no Lua errors. I fixed it by changing the file name to have all lowercase letters. I thought that was insane. Never knew capital letters could keep an addon from working.

**Comment by MinIsMin** [comment]
You're on Linux, right?
And you changed the **folder** name, not the **file** name, am I right?
https://github.com/Tommy228/TTTDamagelogs/blob/master/README.md#installation

**Comment by Monkeys7** [comment]
That makes sense. I would have to check when I get home but seeing as the lowercase letters fixed it I would imagine that the new host I have runs Linux. Thanks for the clarification!
