### ISSUE TITLE
Suggestion: Log when C4 explodes

### ISSUE THREAD

**Issue by iagrib** [Tommy228/TTTDamagelogs#309]

**Comment by MinIsMin** [comment]
TTT Damagelogs uses [the added TTT hooks](https://github.com/Facepunch/garrysmod/pull/1283):
```
hook.Call("TTTC4Arm")
hook.Call("TTTC4Disarm")
hook.Call("TTTC4Destroyed")
hook.Call("TTTC4Pickup")
```
Explode has no hook yet, I'll look into it and create a PR in the [garrysmod repositorie](https://github.com/Facepunch/garrysmod).
