### ISSUE TITLE
[ERROR] addons/tttdamagelogs-3.1.0/lua/damagelogs/client/rdm_manager.lua:833: attempt to call method 'IsActive' (a nil value)

### ISSUE THREAD

**Issue by pelican138** [Tommy228/TTTDamagelogs#313]
[ERROR] addons/tttdamagelogs-3.1.0/lua/damagelogs/client/rdm_manager.lua:833: attempt to call method 'IsActive' (a nil value)
 1. fn - addons/tttdamagelogs-3.1.0/lua/damagelogs/client/rdm_manager.lua:833
   2. unknown - addons/ulib/lua/ulib/shared/hook.lua:109

**Comment by iagrib** [comment]
#339 fixed this issue
