### ISSUE TITLE
oldlogs.lua attempt to index global 'mysqloo' (a nil value)

### ISSUE THREAD

**Issue by masterstreamer** [Tommy228/TTTDamagelogs#316]
After enabling mysql saving and putting in my mysql-data, the following error is shown at version tttdamagelogs-3.1.0:

```
[ERROR] addons/tttdamagelogs-3.1.0/lua/damagelogs/server/oldlogs.lua:23: attempt to index global 'mysqloo' (a nil value)
  1. unknown - addons/tttdamagelogs-3.1.0/lua/damagelogs/server/oldlogs.lua:23
    2. include - [C]:-1
      3. unknown - addons/tttdamagelogs-3.1.0/lua/damagelogs/server/init.lua:23
        4. include - [C]:-1
          5. unknown - addos/tttdamagelogs-3.1.0/lua/autorun/damaglog_autorun.lua:20
```
Any help would be appreciated

**Comment by ZachPL** [comment]
Your mysqloo connection isn't set up correctly, do you have the corresponding mysqloo gmod plugin installed? That error means it can't find the plugin needed to connect to the database.

**Comment by MinIsMin** [comment]
Caused by not having mysqloo installed. Either install it or use `MySQLi`.
If it still throws errors, please comment.
