### ISSUE TITLE
How to manage permissions?

### ISSUE THREAD

**Issue by Robo-Raptor** [Tommy228/TTTDamagelogs#317]
Self explanatory title

**Comment by MinIsMin** [comment]
You can manage the permissions in the [config.lua file](https://github.com/Tommy228/TTTDamagelogs/blob/master/lua/damagelogs/config/config.lua).
TTT Damagelogs supports ranks from Vanilla, ULX and Serverguard.

**Comment by Robo-Raptor** [comment]
Is there an easier way? I have no clue about Lua

**Comment by CSchulz** [comment]
You don't need any experience with Lua to get it working, just have a look at the examples. If you have the opinion there is need for improvement, tell us and we will extend the examples.

**Comment by Robo-Raptor** [comment]
You're right. It was late when I read that so I just didn't pay attention to the contents. Sorry about that
