### ISSUE TITLE
Can't close the 'you've been reported' window even sometimes

### ISSUE THREAD

**Issue by iagrib** [Tommy228/TTTDamagelogs#318]
It stays even after answering all the reports. Condition unknown, happens to everyone from time to time.

**Comment by MinIsMin** [comment]
No lua errors? Nothing happening while clicking on 'X'?

**Comment by iagrib** [comment]
There's no X. No lua errors.

**Comment by Quinlan102** [comment]
If you have to answer a report and you get reported while doing that you get stuck in the answering menu
And you must reconnect to fix it

**Comment by iagrib** [comment]
Yes, it's that your report table gets +1 report in it but it doesn't get updated in the 'you were reported' window. As a result, when you click the 'submit' button, the check for if all reports are answered fails, and the window doesn't autoclose, but new reports don't get displayed anyway.

**Comment by iagrib** [comment]
I checked the code. From what I saw, [here](https://github.com/Tommy228/TTTDamagelogs/blob/a389f50a101a75198aad0aeffbe3ae8fd324fa37/lua/damagelogs/client/rdm_manager.lua#L737) a report gets inserted into the `Damagelog.ReportsQueue` table, and then `BuildReportFrame` is called. However [inside the function itself](https://github.com/Tommy228/TTTDamagelogs/blob/a389f50a101a75198aad0aeffbe3ae8fd324fa37/lua/damagelogs/client/rdm_manager.lua#L26) it checks if the report is in that table and if it is, it does nothing. I don't fully understand why was this done, but from what I can see simply swapping the `table.insert` and `BuildReportFrame` calls should fix the issue.

P. S. I might have missed something, I didn't really try to understand the *whole* code.

**Comment by iagrib** [comment]
I am now replacing the `net.Receive("DL_Report", ...)` part with this on my server:
```lua
net.Receive("DL_SendReport", function()
	local report = net.ReadTable()
	--table.insert(Damagelog.ReportsQueue, report)

	if not LocalPlayer().IsActive or not LocalPlayer():IsActive() then
		BuildReportFrame(report)
	end

	Damagelog.ReportsQueue[#Damagelog.ReportsQueue + 1] = report
end)```

Will report if that works and if it does, create a PR.

**Comment by iagrib** [comment]
Tested; seems to work as intented.
