### ISSUE TITLE
TTT init.lua outputting errors to console

### ISSUE THREAD

**Issue by MeowZedong94** [Tommy228/tttdamagelogs#319]
[ERROR] addons/tttdamagelogs-3.1.0/lua/damagelogs/client/init.lua:172: bad argument #1 to 'IsKeyDown' (number expected, got nil)
  1. IsKeyDown - [C]:-1
   2. Think - addons/tttdamagelogs-3.1.0/lua/damagelogs/client/init.lua:172
    3. fn - addons/tttdamagelogs-3.1.0/lua/damagelogs/client/init.lua:191
     4. unknown - addons/ulib/lua/ulib/shared/hook.lua:109

I have no idea what is going on in the code, it just started doing this the other night.

**Comment by MinIsMin** [comment]
Do you have set the setting `Damagelog.Key` in [config/config.lua](https://github.com/Tommy228/TTTDamagelogs/blob/master/lua/damagelogs/config/config.lua#L23)?

**Comment by MeowZedong94** [comment]
Uh yeah its set to default F8

**Comment by MeowZedong94** [comment]
Its breaking cl_init and cl_voice

**Comment by MinIsMin** [comment]
Seems to be related to #70 .
If you're sure there's no other TTT Damagelogs version on your server, try removing the TTT Damagelogs folder and readding it from source: https://github.com/Tommy228/TTTDamagelogs/releases/tag/v3.1.0

**Comment by MeowZedong94** [comment]
I've done that multiple times and it still outputs the errors.. it was literally the first thing I did when I had the errors crop up.. I am using 3.0.0 right now.. I don't know why the 3.1.0 version is messing with my server

**Comment by MeowZedong94** [comment]
Pointshop from burt0n, fretta mapvote, those are the major ones I can think of

**Comment by iagrib** [comment]
I couldn't recreate this, there must be an issue on your side. Are you sure there aren't any other errors and you're doing complete reinstallation?

**Comment by MinIsMin** [comment]
@MeowZedong94 Does this issue persist? Tested on a server with only ulib and ulx installed and it works.
