### ISSUE TITLE
Missing language strings.

### ISSUE THREAD

**Issue by Satton2** [Tommy228/TTTDamagelogs#322]
While translating this addon on Russian language (_because the official Russian translation is not correct and I don't like it_) I found this missing strings (_found and translated_) that aren't added to the **english.lua** :
![screenshot_20171210112838](https://user-images.githubusercontent.com/23385240/33803293-78a1c066-dd9d-11e7-8bef-51cec0fa5cd6.png)
And another request, can you change «weapon_something» to be «Something»? =)

Directory of this strings: **TTTDamagelogs-master\lua\damagelogs\client\recording.lua**
Lines: **72**, **77**, **111**.

**Comment by MinIsMin** [comment]
Language strings added and weapon names fixed with https://github.com/Tommy228/TTTDamagelogs/commit/82b7ed1e2af1f5ed5fc449960b805dd2ca68282e.
