### ISSUE TITLE
Crash Players with Report

### ISSUE THREAD

**Issue by dasricky** [Tommy228/TTTDamagelogs#326]
Reporting a player with this copypasta will crash the player and disallow them from rejoining the server until it is restarted. Friend showed me this and I tried it, sure enough it worked. Not sure if it's the copypasta or because of how long it is but it does work and needs to be fixed.

★　　★ ° ☾ ☆ ¸. ¸ 　★　 :.　 . • ○ ° ★　 .　 　.　. 　　¸ .　　 ° 　¸. * ● ¸ .　...somewhere　　　° ☾ ° 　¸. ● ¸ .　　★　° :. 　 . • ° 　 .　 *　:.　.　¸ . ● ¸ 　　　★　　★☾ °★ . 　　　 　.　 °☆ 　. ● ¸ .　　　★　° .　 • ○ ° ★　 .　　　　　　 　　.　 ☾ ° 　¸. ...over the rainbow* ● ¸ 　　　　° ☾ °☆ 　. * ¸.　　　★　★ ° . .　 　　¸ .　　 ° 　¸. * ● ¸ .　...way up high　　　° ☾　★ ° . 　 . • ° 　 .　 *　:.　.　¸ . ● ¸ 　　　★　　★☾ °★ . 　　★ ° . .　　　　.　☾ °☆ 　. * ● ¸ .　　　★　° :.　 . • ○ you're a faggot　. 　 ° 　. ● .　　　　° ☾ °☆ 　¸. ● .　　★　　★ ° ☾ ☆ ¸. ¸ 　★　 :.　 . • ○ ° ★　 .　 *　.　. 　　¸ .　　 ° 　¸. * ● ¸ .　　　　° ☾ ° 　¸. ● ¸ .　　★

**Comment by MinIsMin** [comment]
Confirmed. It's not the length but the chars.

**Comment by MinIsMin** [comment]
Removing all letter or digits should circulate it.
It's not good since it also removes things like `! \ "`.
Will look further into it later.

**Comment by Violat0r** [comment]
This might be related to this bug but if someone uses ? ? in their report it will bypass the 10 char requirement.

**Comment by MinIsMin** [comment]
Thanks, I will look into it in a few hours.

**Comment by MinIsMin** [comment]
Now using `%G` as pattern. Doesn't strip `! \ "` but `★ ° ☾ ☆`.
10 char bypass should be fixed too by checking `%G` on client.

**Comment by dasricky** [comment]
Should be able to use more then 10 chars so people can explain situations.

**Comment by Violat0r** [comment]
The 10 character requirement in a minimum requirement, not a maximum.

**Comment by dasricky** [comment]
Also when are spaces coming back or is it always going to be "ithoughtyouwereatsorry."

**Comment by MinIsMin** [comment]
Sorry, the spaces are back with https://github.com/Tommy228/TTTDamagelogs/commit/4d2a1b5edda3b262c14ed5d3fa521ca30c394cf0.
