### ISSUE TITLE
Thanks for deleting

### ISSUE THREAD

**Issue by dasricky** [Tommy228/TTTDamagelogs#328]
In regards to the copypasta report crash, thanks for deleting that..
It was a legitimate issue and nice to see it just gets thrown out.

**Comment by MinIsMin** [comment]
What was deleted?
Your issue isn't deleted, it's closed since it's fixed: https://github.com/Tommy228/TTTDamagelogs/issues/326

**Comment by dasricky** [comment]
Oh! My mistake sorry.
New to Github.
