### ISSUE TITLE
Pls Help to translate, doesnt work.

### ISSUE THREAD

**Issue by JgPfk** [Tommy228/TTTDamagelogs#331]
Can you make a tut how to translate to german, i dont know why but it doesnt work for me.
Pls help.

**Comment by CSchulz** [comment]
You don't need to translate it, because there is already a German translation. Just configure it in the settings.lua.

**Comment by JgPfk** [comment]
I know, i tried, but it doesnt work

**Comment by CSchulz** [comment]
Then please rephrase your problem. What is happening and how it is not working?

**Comment by JgPfk** [comment]
Sry im not at home, can u describe what exactly i have ti do? I know i must be annoying but im a bit dumb in such things (sometimes)

**Comment by iViscosity** [comment]
Are you trying to change it serverside (for everyone) or clientside (for only you)?

If serverside, you want to change [Damagelog.ForcedLanguage = ""](https://github.com/Tommy228/TTTDamagelogs/blob/2fbbd59a6e6417f6f091f6c1313f6f19c9342603/lua/damagelogs/config/config.lua#L111) to "deutsch". 

If you only want to change it for yourself, run the command `ttt_dmglog_language deutsch` in your console.

**Comment by JgPfk** [comment]
In what file is this line for the server?

**Comment by Kroinko** [comment]
For me the clientside works but when I go in the lang.lua file to edit the Damagelog.ForcedLanguage and upload it, then i have just bugs, have i forgot a step? (sry for bad english - austria)

**Comment by JgPfk** [comment]
Had a wrong versipn, i could go with kroinkos steps ahead, ty.

**Comment by JgPfk** [comment]
The line under damgelog.forcedlang.... must be changed.( theres english)
