### ISSUE TITLE
[ERROR] addons/damagelogs/lua/damagelogs/shared/events/ttt_radio.lua:50: bad argument #1 to 'GetNameParam' (string expected, got nil)

### ISSUE THREAD

**Issue by iagrib** [Tommy228/TTTDamagelogs#338]
[ERROR] addons/damagelogs/lua/damagelogs/shared/events/ttt_radio.lua:50: bad argument #1 to 'GetNameParam' (string expected, got nil)
  1. GetNameParam - [C]:-1
   2. ToString - addons/damagelogs/lua/damagelogs/shared/events/ttt_radio.lua:50
    3. AddLogsLine - addons/damagelogs/lua/damagelogs/client/listview.lua:103
     4. SetListViewTable - addons/damagelogs/lua/damagelogs/client/listview.lua:135
      5. func - addons/damagelogs/lua/damagelogs/client/tabs/damagetab.lua:411
       6. unknown - lua/includes/extensions/net.lua:32

**Comment by MinIsMin** [comment]
What were you trying to target with the radio?
It wasn't a player nor a corpse.

**Comment by iagrib** [comment]
This happens when target entity is no longer valid at the moment of radio usage. It's possible for this to happen because you can still use radio on something that you targeted few seconds ago. So if e. g. you target a corpse, it disappears and you say 'corpse is a traitor!' right after that, it will produce this error when viewing logs. Solution: initialize [local variable 'name'](https://github.com/Tommy228/TTTDamagelogs/blob/f42f3021ba30f61024862931a64dd7d1f2a8c3d8/lua/damagelogs/shared/events/ttt_radio.lua#L17) with some value, e. g. `<something>`.

**Comment by MinIsMin** [comment]
I would drop the log if the entity becomes invalid since there aren't any worthwhile information (anymore).

**Comment by iagrib** [comment]
Yeah, that's a better idea. Should I create a PR?
