### ISSUE TITLE
cl_voice.lua spams errors when reports are disabled

### ISSUE THREAD

**Issue by florian2833z** [Tommy228/TTTDamagelogs#351]
If I set Damagelog.RDM_Manager_Enabled to false, cl_voice.lua spams some random errors in the console and no one is able to see who is talking anymore.

**Comment by MinIsMin** [comment]
Should be fixed with https://github.com/Tommy228/TTTDamagelogs/commit/48f7b5f3170bafdbad85159667bcb371add53799.
