### ISSUE TITLE
Hud is broken when reports are disabled

### ISSUE THREAD

**Issue by florian2833z** [Tommy228/tttdamagelogs#352]
This happens if I disable the reports:
Client "Flo" connected (78.50.45.123:27005).
[Flo|54|STEAM_0:1:65321671] Lua Error:

[ERROR] gamemodes/terrortown/gamemode/cl_lang.lua:61: attempt to index upvalue 'cached_active' (a nil value)
  1. GetTranslation - gamemodes/terrortown/gamemode/cl_lang.lua:61
   2. SetMuteState - gamemodes/terrortown/gamemode/cl_voice.lua:579
    3. CycleMuteState - gamemodes/terrortown/gamemode/cl_voice.lua:590
     4. ClearClientState - gamemodes/terrortown/gamemode/cl_init.lua:239
      5. unknown - gamemodes/terrortown/gamemode/cl_init.lua:70

[Flo|54|STEAM_0:1:65321671] Lua Error:

[ERROR] gamemodes/terrortown/gamemode/cl_hud.lua:193: attempt to index local 'L' (a nil value)
  1. SpecHUDPaint - gamemodes/terrortown/gamemode/cl_hud.lua:193
   2. unknown - gamemodes/terrortown/gamemode/cl_hud.lua:331

[Flo|54|STEAM_0:1:65321671] Lua Error:

[ERROR] addons/tttdamagelog/lua/damagelogs/shared/lang.lua:20: attempt to index a nil value
  1. TTTLogTranslate - addons/tttdamagelog/lua/damagelogs/shared/lang.lua:20
   2. unknown - addons/tttdamagelog/lua/damagelogs/client/tabs/old_logs.lua:2
    3. include - [C]:-1
     4. unknown - addons/tttdamagelog/lua/damagelogs/client/init.lua:18
      5. include - [C]:-1
       6. unknown - addons/tttdamagelog/lua/autorun/damagelog_autorun.lua:22

[Flo|54|STEAM_0:1:65321671] Lua Error:

[ERROR] addons/tttdamagelog/lua/damagelogs/shared/lang.lua:20: attempt to index a nil value
  1. TTTLogTranslate - addons/tttdamagelog/lua/damagelogs/shared/lang.lua:20
   2. CreateShotsPanel - addons/tttdamagelog/lua/damagelogs/client/recording.lua:72
    3. fn - addons/tttdamagelog/lua/damagelogs/client/recording.lua:144
     4. unknown - lua/ulib/shared/hook.lua:109

[Flo|54|STEAM_0:1:65321671] Lua Error:

[ERROR] gamemodes/terrortown/gamemode/cl_hud.lua:193: attempt to index local 'L' (a nil value)
  1. SpecHUDPaint - gamemodes/terrortown/gamemode/cl_hud.lua:193
   2. unknown - gamemodes/terrortown/gamemode/cl_hud.lua:331

[Flo|54|STEAM_0:1:65321671] Lua Error:

[ERROR] gamemodes/terrortown/gamemode/cl_hud.lua:193: attempt to index local 'L' (a nil value)
  1. SpecHUDPaint - gamemodes/terrortown/gamemode/cl_hud.lua:193
   2. unknown - gamemodes/terrortown/gamemode/cl_hud.lua:331

[Flo|54|STEAM_0:1:65321671] Lua Error:

[ERROR] gamemodes/terrortown/gamemode/cl_hud.lua:193: attempt to index local 'L' (a nil value)
  1. SpecHUDPaint - gamemodes/terrortown/gamemode/cl_hud.lua:193
   2. unknown - gamemodes/terrortown/gamemode/cl_hud.lua:331

**Comment by MinIsMin** [comment]
I currently can not reproduce a broken HUD on a server without any other addons.

Do you use a custom HUD?
What version of TTT Damagelogs are you using? (e.g. GitHub master or a GitHub release)
When do these lua errors appear? (e.g. during gameplay, loading old logs from 2.4)

**Comment by florian2833z** [comment]
At the moment, this doesnt occur anymore. I will write here if it occurs again.
