### ISSUE TITLE
#362 breaks names

### ISSUE THREAD

**Issue by Violat0r** [Tommy228/tttdamagelogs#367]
Breaks damage log names

[Broken names](https://i.imgur.com/CFxBefA.png)

**Comment by Violat0r** [comment]
Looks like death senses and shot logs might be broken as well

**Comment by Tommy228** [comment]
Thanks, it's reverted for now.

**Comment by Alf21** [comment]
Yea i did a mistake, sorry

**Comment by MinIsMin** [comment]
Should be fixed with https://github.com/Tommy228/tttdamagelogs/pull/361.
