### ISSUE TITLE
Cslays command - no permission

### ISSUE THREAD

**Issue by SilverLithium** [Tommy228/tttdamagelogs#378]
I can't use the cslays command even as superadmin. Says: You do not have access to this command.
It's also nowhere in the ulx menu to set as permission, I also can't see it anywhere in config.

How can I set ranks to use cslays ? Am I missing something ?

Version 3.0.0.

**Comment by MicrosoftMCreates** [comment]
The cslays command should be under the TTT section of the ULX command menu where aslay and aslayid are. If it isnt under that section go to ULX->Groups tab on the menu and Select the superadmin group_> Manage permissions, You can enable the command from there.

**Comment by SilverLithium** [comment]
It's not there.
