### ISSUE TITLE
TTT2 Support

### ISSUE THREAD

**Issue by dok441** [Tommy228/tttdamagelogs#379]
[ERROR] addons/tttdamagelogs-master/lua/damagelogs/server/autoslay.lua:397: attempt to call method 'HasTeamRole' (a nil value)
  1. fn - addons/tttdamagelogs-master/lua/damagelogs/server/autoslay.lua:397
   2. Call - addons/ulib/lua/ulib/shared/hook.lua:109
    3. unknown - gamemodes/terrortown/gamemode/server/sv_main.lua:928

Timer Failed! [prep2begin][@gamemodes/terrortown/gamemode/server/sv_main.lua (line 723)]
no work https://github.com/Alf21/TTT2

**Comment by Alf21** [comment]
You are using an old version. Use my version instead, it's already fixed

**Comment by dok441** [comment]
She's fixed, but it has its bugs, like not working the murder at the steam ID.
