### ISSUE TITLE
Report Manager Doesn't Work

### ISSUE THREAD

**Issue by jimbo619y2j** [Tommy228/tttdamagelogs#380]
As of about a week or so ago, the report manager for damage logs completely stopped working. When you go to click on "submit" for !report, nothing happens.

**Comment by derekstephen** [comment]
@jimbo619y2j What version are you using? And are there any errors in the server logs?

**Comment by jimbo619y2j** [comment]
The most recent version (assuming 3.0?) No LUA errors in-game or in rcon. Tried uninstalling and re-installing the add-on, un-installing and re-installing ULX to see if that was the issue, but no dice. Not sure what the issue is.

**Comment by jimbo619y2j** [comment]
Nevermind it was a weird problem with a conflicting add-on. Fixed it. Thanks anyway though.
