### ISSUE TITLE
Download website for oldlogs

### ISSUE THREAD

**Issue by TuXEKRO** [Tommy228/tttdamagelogs#383]
Hello, I'm sorry because I think it's not the indicated section, it's the first time I post on Github.

I have the following problem and I can not find where to download the web part to be able to view the old records from a web page.
I have the backup of 2015 but there are several things that have changed since then, and currently it does not work.

Thanks and best regards!

**Comment by MinIsMin** [comment]
The old website code can be found here: https://github.com/Tommy228/tttdamagelogs/tree/efdbd0fc6aa7943dee50949c35249c42648ad1a6/website_code

**Comment by TuXEKRO** [comment]
Thank you, are there news of whether you are going out for the new version?

**Comment by MinIsMin** [comment]
Currently nothing is planned.
