### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by deinemudda32** [Tommy228/TTTDamagelogs#71]
[ERROR] addons/rdm/lua/damagelogs/sv_damageinfos.lua:10: attempt to call method 'Nick' (a nil value)
  1. shootCallback - addons/rdm/lua/damagelogs/sv_damageinfos.lua:10
   2. unknown - addons/rdm/lua/damagelogs/sv_damageinfos.lua:54

i get this error randomly in my console.

**Comment by Tommy228** [comment]
Fixed on experimental
