### ISSUE TITLE
Missing status for waiting victim's decision to reported player's response

### ISSUE THREAD

**Issue by CSchulz** [Tommy228/TTTDamagelogs#74]
I found out that the status waiting for victim player is missing after the reported player has responded

**Comment by Tommy228** [comment]
Welp I don't understand, explain more please?

**Comment by CSchulz** [comment]
At the moment the reported player answers the report and the victim gets the answer and can decide.

From admin view it isn't possible to see if the victim has decided already. You just get a notice if the victim cancels.
I am missing the state "Waiting for victims decision".

**Comment by Tommy228** [comment]
Ah ok, got it
