### ISSUE TITLE
RDM-Manager opens current round per default

### ISSUE THREAD

**Issue by Joschasa** [Tommy228/TTTDamagelogs#78]
There is a warning involved, if someone views the current round while he is alive. That's fine.

But if he just wants to view something from last round, this warning makes other admins suspicious - even if he didn't really look at the current log. Maybe show the last round per default?

Moreover: If someone is allowed to view the Reports, but not the current (active) round, he still can see the reports from the current round. So it would be great, if he could not see the reports of the current&active round.

**Comment by Sjokomelk** [comment]
Add an option too?

**Comment by Tommy228** [comment]
I'll add a clientside option on F1.
