### ISSUE TITLE
Show notifications at end of the round

### ISSUE THREAD

**Issue by Joschasa** [Tommy228/TTTDamagelogs#79]
The current notification system "leaks" crucial information, which can result in a less enjoyable game experience for admins (talking about TTT here).

With the old random manager it was already possible to know wether a killer is innocent, if some seconds after he shot somebody a report notification pops up. The new system even contains the names of victim and reporter, so one can even get informations about kills he didn't even witness.

Possible fixes:
- Don't show notifications to alive players / admins
- Collect notifications for alive admins and let them get an overview of what happend at his dead / end of the round
- Option to disable notifications alltogether

**Comment by Sjokomelk** [comment]
The "Player will be autoslayed next round for "reason" should either not pop up for alive players, or wait until next round. As this can disclose if a player is traitor or innocent.

**Comment by Tommy228** [comment]
I figured out hiding the names of the notifications to alive admins is a much better option for a lazy person like me.

Also I couldn't find anything on ULX that would let me hide the logs to certain players, I'll try editing the default ulx functions.

**Comment by Sjokomelk** [comment]
Just admins? You need to hide the name of the player.

**Comment by Tommy228** [comment]
I mean players. Also, I just did the ULX edit.
