### ISSUE TITLE
Cancel by admin with reason

### ISSUE THREAD

**Issue by CSchulz** [Tommy228/TTTDamagelogs#81]
It would be nice to have the possibility to cancel a report with a reason as admin.

Sometimes people forget what they have done and report other players.

**Comment by Tommy228** [comment]
I added a conclusion system for that.

**Comment by CSchulz** [comment]
Is there no window for the victim and the reported player which contains the conclusion?

**Comment by Tommy228** [comment]
Not yet

**Comment by CSchulz** [comment]
Oh I thought ... This would be nice.
