### ISSUE TITLE
Damagelog on webserver still acting weird

### ISSUE THREAD

**Issue by Sjokomelk** [Tommy228/TTTDamagelogs#84]
See picture

http://Gyazo.KennethD.net/i/AlVcv.png

**Comment by Tommy228** [comment]
The picture is outdated. Now that I'm working on the repo, can you upload it again please?

**Comment by Sjokomelk** [comment]
http://puu.sh/e6FCX/e71ff59c94.png

Not all rounds show up, maps are unsorted. Don't know if it deletes old records like it's supposed to. 
Damage log can be viewed here http://hjortefjellet.no/dmglog/
