### ISSUE TITLE
clientside error listview

### ISSUE THREAD

**Issue by ZachPL** [Tommy228/TTTDamagelogs#87]
[ERROR] lua/damagelogs/cl_listview.lua:128: bad argument #1 to 'pairs' (table expected, got nil)
  1. pairs - [C]:-1
   2. SetRolesListView - lua/damagelogs/cl_listview.lua:128
    3. v - lua/damagelogs/cl_tabs/damagetab.lua:6
     4. unknown - lua/includes/modules/cvars.lua:49

**Comment by Tommy228** [comment]
Fixed.
