### ISSUE TITLE
Enhancements and Fixes

### ISSUE THREAD

**Issue by BuilderGaming** [Tommy228/TTTDamagelogs#93]
Hi,

So I suggested we get the updated version on a server called Serious TTT. They stuck with it for like 4 hours and then removed and and are currently sticking with version 1. I asked why the removed it and these are the reasons. Please fix or add them. 
![6c8ccc849670f6eac12c27c06f6a476b](https://cloud.githubusercontent.com/assets/8619739/5444017/e03a0f92-8474-11e4-9e5f-369f813e013e.png)

**Comment by Tommy228** [comment]
Most of those have already been reported, I'm working on it now
