### ISSUE TITLE
Common error on admin join

### ISSUE THREAD

**Issue by petravic** [Tommy228/TTTDamagelogs#94]
[ERROR] lua/includes/modules/net.lua:172: net.ReadType: Couldn't read type 214
  1. error - [C]:-1
   2. ReadType - lua/includes/modules/net.lua:172
    3. ReadType - lua/includes/modules/net.lua:116
     4. ReadType - lua/includes/modules/net.lua:116
      5. ReadType - lua/includes/modules/net.lua:116
       6. ReadType - lua/includes/modules/net.lua:116
        7. ReadType - lua/includes/modules/net.lua:116
         8. ReadTable - lua/includes/modules/net.lua:116
          9. func - addons/damagelogs/lua/damagelogs/cl_tabs/rdm_manager.lua:348
           10. unknown - lua/includes/modules/net.lua:32

**Comment by Darksider-** [comment]
It's actually on [line 285 of rdm_manager.lua](https://github.com/Tommy228/TTTDamagelogs/blob/master/lua/damagelogs/cl_tabs/rdm_manager.lua#L285) if you don't have it edited. We're getting the same error, but "Couldn't read type 214" is sometimes another number. Last one we got is "type 97".

**Comment by Tommy228** [comment]
Can you run this command using your rcon and show me the result?
`lua_run PrintTable(Damagelog.Reports)`

**Comment by petravic** [comment]
Oh yeah i edited my version but i have changed my index to 16 bits before tommy did update and issue is still there like reports index glitched and you cant change status or see what player responded

**Comment by petravic** [comment]
So error on join:

[ERROR] lua/includes/modules/net.lua:172: net.ReadType: Couldn't read type 80
  1. error - [C]:-1
   2. ReadType - lua/includes/modules/net.lua:172
    3. ReadType - lua/includes/modules/net.lua:112
     4. ReadType - lua/includes/modules/net.lua:116
      5. ReadTable - lua/includes/modules/net.lua:116
       6. func - addons/damagelogs/lua/damagelogs/cl_tabs/rdm_manager.lua:348
        7. unknown - lua/includes/modules/net.lua:32
And print table:
http://pastebin.com/2fHABek2
Enjoy

**Comment by petravic** [comment]
Another bug is if you are on server and there is like 3 reports and then you leave and come back reports will start back from index 1 but they will like overrite old ones from last session and you cant update status or see response

**Comment by Tommy228** [comment]
Alright, I see how I can fix this

**Comment by Tommy228** [comment]
Fixed. ed801cd16094274e3be5c585db4a2f8a513004a3
