### ISSUE TITLE
More information during death scene

### ISSUE THREAD

**Issue by Sjokomelk** [Tommy228/TTTDamagelogs#97]
I see more potential for death scene. Right now you can only see if the player hits the other player, this doesn't always show up either. (sometimes you need slow mode on to see the red lines). I have one suggestion, add the shot log to the side, and the shots made during the time will be hovered over as the player shoots.

A longer timeline would also be appreciated, just add the start point to the timeline.

**Comment by Tommy228** [comment]
Not sure if I'll do this right now but good ideas

**Comment by Sjokomelk** [comment]
Please do it whenever you can, me and my moderators see little use in it right now, because it doesn't deliver much helpful information. It's almost impossible to see what's happening.

**Comment by CSchulz** [comment]
Perhaps a step by step function which additional information like described above would be nice.

**Comment by BuilderGaming** [comment]
Also add if a player's corpse is ID on UNID. that would be nice
