### ISSUE TITLE
Question system?

### ISSUE THREAD

**Issue by Sjokomelk** [Tommy228/TTTDamagelogs#98]
Right now it's hard to keep the dialogue up with the players in the report, especially if there are many players on the server. One way to deal with this is
1. Admin sends a response to the report
2. Both players get the respond screen back, with the buttons: Cancel report, Answer administrator message.
3. Administrator now has more information about what happened and can then make a decision.

**Comment by Tommy228** [comment]
I thought about a chat system, wouldn't that be better? An admin can open a chat from the "Take action", button. Then I can make it look like the iOS/Android Message app. It's not hard, it's just going to take time.

**Comment by Sjokomelk** [comment]
As long as it's easy to use, and does the job, I don't really care about how it looks :p

**Comment by CSchulz** [comment]
I don't understand why you need it. I had never a situation for the current round (when shot logs are available) that it wasn't possible for me to understand what happened.

**Comment by petravic** [comment]
yeah chat it better idea

**Comment by Tommy228** [comment]
Started working on this. Here's what it currently looks like 

![Preview](http://image.noelshack.com/fichiers/2015/13/1427132372-capture.jpg)

Ideas are welcome

**Comment by CSchulz** [comment]
Do you have some pictures how messages look like?

How would be the "workflow"?

Player X reports Y, they start talking ... No result is found and admin can stop the chat with a conclusion and an action.

**Comment by Tommy228** [comment]
Finished in the dev branch, now testing it.

**Comment by comedinha** [comment]
What to do when are 3 active reports?

**Comment by CyberAP** [comment]
My suggestions:

* If you click 'Open chat' you don't need to set report state to 'In progress'. That's really disturbing and slows down the work.
* Change 'Close chat' functionality and rename it to 'Finish report'. It should ask you for a conclusion and for action (or no action) like autoslay. Conclusion is visible to all players in chat until they close it. Default slay reason in that case should be taken from a conclusion.
* Invited players should have a 'Witness' status or something like that, not a 'Reported' like it's now.

**Comment by Tommy228** [comment]
Yeah, it still needs a lot of work. Thanks for the feedback

**Comment by Linkfan123** [comment]
Maybe this can totally replace the response system in place in some point.
But we all know that isn't going to happen very soon. :3
:+1:
